using System;
using System.Collections.ObjectModel;

namespace NeoEditor.Player.Core.Logging;

/// <summary>One log line forwarded from the host page (console / clipboard / onerror).</summary>
public sealed class PlayerLogLine
{
    public PlayerLogLine(string level, string message)
    {
        Timestamp = DateTime.Now;
        Level = level;
        Message = message;
    }

    public DateTime Timestamp { get; }
    public string Level { get; }
    public string Message { get; }
}

/// <summary>One page run (run id generated by host.html) with its captured lines.</summary>
public sealed class PlayerRunRecord
{
    public PlayerRunRecord(string runId)
    {
        RunId = runId;
        StartedAt = DateTime.Now;
    }

    public string RunId { get; }
    public DateTime StartedAt { get; }
    public ObservableCollection<PlayerLogLine> Lines { get; } = [];
}

/// <summary>Raised with the exact line that was appended (file sinks need the content).</summary>
public sealed class PlayerLogLineAppendedEventArgs : EventArgs
{
    public PlayerLogLineAppendedEventArgs(string runId, PlayerLogLine line)
    {
        RunId = runId;
        Line = line;
    }

    public string RunId { get; }
    public PlayerLogLine Line { get; }
}

/// <summary>
/// In-memory run log store (Docs/42 §3.8 / P5.3): SwfLogBridge appends forwarded page
/// batches here, and the player's log viewer binds to <see cref="Runs"/>. One record per
/// page run; UI-thread marshaling is the host's responsibility (LogAdded event).
/// </summary>
public sealed class RunLogStore
{
    private readonly object _gate = new();

    public ObservableCollection<PlayerRunRecord> Runs { get; } = [];

    /// <summary>Raised after every append/clear — hosts refresh their view on the UI thread.</summary>
    public event EventHandler? LogAdded;

    /// <summary>Raised with the exact appended line (same thread as Append — for file sinks).</summary>
    public event EventHandler<PlayerLogLineAppendedEventArgs>? LineAppended;

    public PlayerRunRecord? CurrentRun { get; private set; }

    public void Append(string runId, string level, string message)
    {
        if (string.IsNullOrEmpty(message)) return;

        PlayerLogLine? line = null;
        lock (_gate)
        {
            if (CurrentRun is null || !string.Equals(CurrentRun.RunId, runId, StringComparison.Ordinal))
            {
                CurrentRun = new PlayerRunRecord(runId);
                Runs.Add(CurrentRun);
            }

            line = new PlayerLogLine(level, message);
            CurrentRun.Lines.Add(line);
        }

        LogAdded?.Invoke(this, EventArgs.Empty);
        if (line is not null)
            LineAppended?.Invoke(this, new PlayerLogLineAppendedEventArgs(runId, line));
    }

    public void Clear()
    {
        lock (_gate)
        {
            Runs.Clear();
            CurrentRun = null;
        }

        LogAdded?.Invoke(this, EventArgs.Empty);
    }
}
