<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>NeoEditor.Plugins.Cli</RootNamespace>
        <NoWarn>CS8618;CS9264</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NeoEditor.Core\NeoEditor.Core.csproj" />
        <ProjectReference Include="..\NeoEditor.Infra\NeoEditor.Infra.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
