<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>NeoEditor.Plugins.ImageTools</RootNamespace>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <NoWarn>CS8618;CS9264</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NeoEditor.Core\NeoEditor.Core.csproj" />
        <ProjectReference Include="..\NeoEditor.Infra\NeoEditor.Infra.csproj" />
        <ProjectReference Include="..\NeoEditor.UI.Common\NeoEditor.UI.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NeoEditor.Infra.Services" />
        <Using Include="NeoEditor.UI.Common.Services" />
        <Using Include="NeoEditor.UI.Common.Visualizers" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="ProDataGrid" Version="12.0.4" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="FluentIcons.Avalonia" Version="2.1.333" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>
</Project>
