using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using NeoEditor.Data.Model;
using NeoEditor.Data.Model.Game;
using Xunit;

namespace NeoEditor.Core.Tests.Model;

/// <summary>
/// R30: authoritative field descriptions embedded from Docs/38-full-field-reference.md
/// (generated by artifacts/gen-field-descriptions.js). The coverage test below is the
/// source of truth that every [Column] property of every game entity has an explanation —
/// a missing entry fails the build and must be added to the alias/supplement tables.
/// </summary>
public class FieldDescriptionsTests
{
    private static IEnumerable<Type> EntityTypes()
        => typeof(IEntity).Assembly.GetTypes()
            .Where(t => t.Namespace == "NeoEditor.Data.Model.Game"
                        && t.GetCustomAttribute<TableAttribute>() != null);

    [Fact]
    public void AllColumnProperties_HaveDescriptions()
    {
        var missing = new List<string>();
        foreach (var type in EntityTypes())
        {
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                         .Where(p => p.GetCustomAttribute<ColumnAttribute>() != null
                                     && p.DeclaringType != typeof(IEntity)))
            {
                if (FieldDescriptions.GetDescription(type, prop.Name) is null)
                    missing.Add($"{type.Name}.{prop.Name}");
            }
        }

        Assert.True(missing.Count == 0,
            $"Fields without descriptions: {string.Join(", ", missing)}");
    }

    [Fact]
    public void AllColumnProperties_HaveNonTrivialDescriptions()
    {
        foreach (var type in EntityTypes())
        {
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                         .Where(p => p.GetCustomAttribute<ColumnAttribute>() != null
                                     && p.DeclaringType != typeof(IEntity)))
            {
                var desc = FieldDescriptions.GetDescription(type, prop.Name);
                Assert.NotNull(desc);
                Assert.True(desc!.Length >= 4, $"Description too short for {type.Name}.{prop.Name}: '{desc}'");
            }
        }
    }

    [Fact]
    public void EditorInternalColumns_HaveWildcardDescriptions()
    {
        // ModId / FilePath / EntityId live on IEntity and apply to every table ("*." prefix).
        Assert.NotNull(FieldDescriptions.GetDescription("attackmodes", "ModId"));
        Assert.NotNull(FieldDescriptions.GetDescription("itemtypes", "FilePath"));
        Assert.NotNull(FieldDescriptions.GetDescription("recipes", "EntityId"));
    }

    [Fact]
    public void Lookup_IsCaseInsensitive()
    {
        var viaLower = FieldDescriptions.GetDescription("attackmodes", "Id");
        Assert.NotNull(viaLower);
        Assert.Equal(viaLower, FieldDescriptions.GetDescription("AttackModes", "id"));
    }

    [Fact]
    public void KnownFields_CarryMeaningfulText()
    {
        // Spot checks against Doc 38 semantics.
        var id = FieldDescriptions.GetDescription(typeof(AttackMode), nameof(AttackMode.Id));
        Assert.Contains("唯一标识", id);

        var damageCut = FieldDescriptions.GetDescription(typeof(AttackMode), nameof(AttackMode.DamageCut));
        Assert.Contains("切割伤害", damageCut);

        var treasures = FieldDescriptions.GetDescription(typeof(TreasureTable), nameof(TreasureTable.Treasures));
        Assert.NotNull(treasures);
        Assert.Contains("复合列", treasures!); // Doc 37 §5.2 复合列摘要

        var condId = FieldDescriptions.GetDescription(typeof(ItemType), nameof(ItemType.CondId));
        Assert.Contains("Condition", condId);
    }
}
