package
{
   import flash.display.BitmapData;
   import flash.display.StageScaleMode;
   import flash.geom.Matrix;
   import flash.utils.Dictionary;
   import org.flixel.FlxObject;
   import org.flixel.FlxPoint;
   
   public class GUIValues
   {
      
      public static const GUITYPE_800X450:uint = 0;
      
      public static const GUITYPE_1024X768:uint = 1;
      
      public static const GUITYPE_1360X768:uint = 2;
      
      public static const GUITYPE_1600X900:uint = 3;
      
      public static const GUITYPE_2400X1350:uint = 4;
      
      private static var m_nGUIType:uint;
      
      public static var m_fItemZoom:Number;
      
      public static var m_fCamZoom:Number;
      
      public static var m_bOverrideZoom:Boolean;
      
      private static var m_vDicts:Vector.<Dictionary>;
      
      private static var ptTemp:FlxPoint;
       
      
      public function GUIValues()
      {
         super();
      }
      
      public static function SetRes(param1:uint) : void
      {
         m_nGUIType = param1;
      }
      
      public static function GetRes() : uint
      {
         return m_nGUIType;
      }
      
      public static function Initialize() : void
      {
         var _loc2_:Object = null;
         ptTemp = new FlxPoint();
         m_vDicts = new Vector.<Dictionary>();
         m_vDicts.push(new Dictionary());
         m_vDicts.push(new Dictionary());
         m_vDicts.push(new Dictionary());
         m_vDicts.push(new Dictionary());
         m_vDicts.push(new Dictionary());
         var _loc1_:FlxPoint = new FlxPoint();
         m_fItemZoom = 1;
         m_fCamZoom = 1;
         m_bOverrideZoom = true;
         _loc1_ = new FlxPoint(280,159);
         m_vDicts[0]["EndState.m_btnPlay"] = new FlxPoint(_loc1_.x + 132,_loc1_.y + 296);
         m_vDicts[0]["EndState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 162,_loc1_.y + 356);
         m_vDicts[0]["EndState.sprPlayer"] = new FlxPoint(_loc1_.x + 95,_loc1_.y + 188);
         m_vDicts[0]["GameOverState.m_btnPlay"] = new FlxPoint(_loc1_.x + 70,_loc1_.y + 132);
         m_vDicts[0]["GameOverState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 100,_loc1_.y + 192);
         m_vDicts[0]["GameOverState.sprGameOver"] = new FlxPoint(_loc1_.x + 50,_loc1_.y + 28);
         m_vDicts[0]["GameOverState.sprPlayer"] = new FlxPoint(_loc1_.x + 290,_loc1_.y + 18);
         m_vDicts[0]["GameOverState.txtConds"] = new FlxPoint(_loc1_.x + 542,_loc1_.y + 10);
         m_vDicts[0]["GameOverState.txtConds.width"] = 254;
         m_vDicts[0]["GameOverState.txtLog"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 225);
         m_vDicts[0]["GameOverState.txtLog.width"] = 254;
         m_vDicts[0]["GameOverState.txtStats"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 140);
         m_vDicts[0]["GameOverState.txtStats.width"] = 254;
         m_vDicts[0]["GUIBattleScreen.btnNextEnemy"] = new FlxPoint(_loc1_.x + 516,_loc1_.y + 78);
         m_vDicts[0]["GUIBattleScreen.btnPrevEnemy"] = new FlxPoint(_loc1_.x + 498,_loc1_.y + 78);
         m_vDicts[0]["GUIBattleScreen.NumLines"] = 5;
         m_vDicts[0]["GUIBattleScreen.sprEnemy"] = new FlxPoint(_loc1_.x + 465,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.sprEnemyMove"] = new FlxPoint(_loc1_.x + 611,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.sprEnemyNext"] = new FlxPoint(_loc1_.x + 488,_loc1_.y + -10);
         m_vDicts[0]["GUIBattleScreen.sprEnemyPanel"] = new FlxPoint(_loc1_.x + 476,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.sprEnemyPrev"] = new FlxPoint(_loc1_.x + 444,_loc1_.y + -10);
         m_vDicts[0]["GUIBattleScreen.sprEnemyTarget"] = new FlxPoint(_loc1_.x + 652,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.sprHex"] = new FlxPoint(_loc1_.x + 349,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.sprPlayerImg"] = new FlxPoint(_loc1_.x + 44,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.sprPlayerMoveImg"] = new FlxPoint(_loc1_.x + 180,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.sprPlayerPanel"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.sprPlayerPanel.image"] = "GUIBattlePanel.png";
         m_vDicts[0]["GUIBattleScreen.sprPlayerTargetImg"] = new FlxPoint(_loc1_.x + 230,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.txtEnemyFields"] = new FlxPoint(_loc1_.x + 553,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.txtEnemyFields.width"] = 58;
         m_vDicts[0]["GUIBattleScreen.txtEnemyFields2"] = new FlxPoint(_loc1_.x + 485,_loc1_.y + 102);
         m_vDicts[0]["GUIBattleScreen.txtEnemyFields2.width"] = 132;
         m_vDicts[0]["GUIBattleScreen.txtEnemyName"] = new FlxPoint(_loc1_.x + 476,_loc1_.y + 60);
         m_vDicts[0]["GUIBattleScreen.txtEnemyName.width"] = 78;
         m_vDicts[0]["GUIBattleScreen.txtEnemyVals"] = new FlxPoint(_loc1_.x + 613,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.txtEnemyVals.width"] = 122;
         m_vDicts[0]["GUIBattleScreen.txtEnemyVals2"] = new FlxPoint(_loc1_.x + 545,_loc1_.y + 102);
         m_vDicts[0]["GUIBattleScreen.txtEnemyVals2.width"] = 114;
         m_vDicts[0]["GUIBattleScreen.txtEnemyVs"] = new FlxPoint(_loc1_.x + 659,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.txtHexFields"] = new FlxPoint(_loc1_.x + 334,_loc1_.y + 87);
         m_vDicts[0]["GUIBattleScreen.txtHexFields.width"] = 83;
         m_vDicts[0]["GUIBattleScreen.txtHexVals"] = new FlxPoint(_loc1_.x + 396,_loc1_.y + 87);
         m_vDicts[0]["GUIBattleScreen.txtHexVals.width"] = 80;
         m_vDicts[0]["GUIBattleScreen.txtPlayerFields"] = new FlxPoint(_loc1_.x + 122,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.txtPlayerFields.width"] = 58;
         m_vDicts[0]["GUIBattleScreen.txtPlayerFields2"] = new FlxPoint(_loc1_.x + 72,_loc1_.y + 102);
         m_vDicts[0]["GUIBattleScreen.txtPlayerFields2.width"] = 132;
         m_vDicts[0]["GUIBattleScreen.txtPlayerName"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 60);
         m_vDicts[0]["GUIBattleScreen.txtPlayerName.width"] = 54;
         m_vDicts[0]["GUIBattleScreen.txtPlayerVals"] = new FlxPoint(_loc1_.x + 182,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.txtPlayerVals.width"] = 122;
         m_vDicts[0]["GUIBattleScreen.txtPlayerVals2"] = new FlxPoint(_loc1_.x + 133,_loc1_.y + 102);
         m_vDicts[0]["GUIBattleScreen.txtPlayerVals2.width"] = 114;
         m_vDicts[0]["GUIBattleScreen.txtPlayerVs"] = new FlxPoint(_loc1_.x + 225,_loc1_.y + 3);
         m_vDicts[0]["GUIBattleScreen.WeatherNode"] = new FlxPoint(_loc1_.x + 435,_loc1_.y + 0);
         m_vDicts[0]["GUIBattleScreen.zoom"] = 1;
         m_vDicts[0]["GUIEscMenu.m_btn1024"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 107);
         m_vDicts[0]["GUIEscMenu.m_btn1360"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 133);
         m_vDicts[0]["GUIEscMenu.m_btn1600"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 135);
         m_vDicts[0]["GUIEscMenu.m_btn2400"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 161);
         m_vDicts[0]["GUIEscMenu.m_btn800"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 81);
         m_vDicts[0]["GUIEscMenu.m_btnAUTO"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 55);
         m_vDicts[0]["GUIEscMenu.m_btnAutosave"] = new FlxPoint(_loc1_.x + 514,_loc1_.y + 321);
         m_vDicts[0]["GUIEscMenu.m_btnBBG"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 347);
         m_vDicts[0]["GUIEscMenu.m_btnCancel"] = new FlxPoint(_loc1_.x + 408,_loc1_.y + 230);
         m_vDicts[0]["GUIEscMenu.m_btnCredits"] = new FlxPoint(_loc1_.x + 359,_loc1_.y + 264);
         m_vDicts[0]["GUIEscMenu.m_btnExit"] = new FlxPoint(_loc1_.x + 329,_loc1_.y + 136);
         m_vDicts[0]["GUIEscMenu.m_btnFilter"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 347);
         m_vDicts[0]["GUIEscMenu.m_btnFPSDn"] = new FlxPoint(_loc1_.x + 514,_loc1_.y + 55 + 124);
         m_vDicts[0]["GUIEscMenu.m_btnFPSUp"] = new FlxPoint(_loc1_.x + 514 + 74 + 26,_loc1_.y + 55 + 124);
         m_vDicts[0]["GUIEscMenu.m_btnFullscreen"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 321);
         m_vDicts[0]["GUIEscMenu.m_btnGreenlight"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 432);
         m_vDicts[0]["GUIEscMenu.m_btnInstr"] = new FlxPoint(_loc1_.x + 359,_loc1_.y + 238);
         m_vDicts[0]["GUIEscMenu.m_btnLoad"] = new FlxPoint(_loc1_.x + 329,_loc1_.y + 16);
         m_vDicts[0]["GUIEscMenu.m_btnMain"] = new FlxPoint(_loc1_.x + 55,_loc1_.y + 164);
         m_vDicts[0]["GUIEscMenu.m_btnManual"] = new FlxPoint(_loc1_.x + 27,_loc1_.y + 28);
         m_vDicts[0]["GUIEscMenu.m_btnMasterDn"] = new FlxPoint(_loc1_.x + 514,_loc1_.y + 55);
         m_vDicts[0]["GUIEscMenu.m_btnMasterUp"] = new FlxPoint(_loc1_.x + 514 + 74 + 26,_loc1_.y + 55);
         m_vDicts[0]["GUIEscMenu.m_btnMusicDn"] = new FlxPoint(_loc1_.x + 514,_loc1_.y + 55 + 36);
         m_vDicts[0]["GUIEscMenu.m_btnMusicUp"] = new FlxPoint(_loc1_.x + 514 + 74 + 26,_loc1_.y + 55 + 36);
         m_vDicts[0]["GUIEscMenu.m_btnMute"] = new FlxPoint(_loc1_.x + 710,_loc1_.y + 11);
         m_vDicts[0]["GUIEscMenu.m_btnOptions"] = new FlxPoint(_loc1_.x + 359,_loc1_.y + 212);
         m_vDicts[0]["GUIEscMenu.m_btnOK"] = new FlxPoint(_loc1_.x + 329,_loc1_.y + 230);
         m_vDicts[0]["GUIEscMenu.m_btnPlay"] = new FlxPoint(_loc1_.x + 329,_loc1_.y + 85);
         m_vDicts[0]["GUIEscMenu.m_btnReset"] = new FlxPoint(_loc1_.x + 359,_loc1_.y + 238);
         m_vDicts[0]["GUIEscMenu.m_btnSoundDn"] = new FlxPoint(_loc1_.x + 514,_loc1_.y + 55 + 72);
         m_vDicts[0]["GUIEscMenu.m_btnSoundUp"] = new FlxPoint(_loc1_.x + 514 + 74 + 26,_loc1_.y + 55 + 72);
         m_vDicts[0]["GUIEscMenu.m_btnStretch"] = new FlxPoint(_loc1_.x + 338,_loc1_.y + 373);
         m_vDicts[0]["GUIEscMenu.m_btnTerEdit"] = new FlxPoint(_loc1_.x + 345,_loc1_.y + 298);
         m_vDicts[0]["GUIEscMenu.m_btnWiki"] = new FlxPoint(_loc1_.x + 27,_loc1_.y + 93);
         m_vDicts[0]["GUIEscMenu.m_btnZomboid"] = new FlxPoint(_loc1_.x + 493,_loc1_.y + 432);
         m_vDicts[0]["GUIEscMenu.m_sprBugsBG"] = new FlxPoint(_loc1_.x + 139,_loc1_.y + 432);
         m_vDicts[0]["GUIEscMenu.m_sprCredits"] = new FlxPoint(_loc1_.x + 400,_loc1_.y + 225);
         m_vDicts[0]["GUIEscMenu.m_sprDialogBG"] = new FlxPoint(_loc1_.x + 325,_loc1_.y + 190);
         m_vDicts[0]["GUIEscMenu.m_sprDialogBG.size"] = new FlxPoint(150,70);
         m_vDicts[0]["GUIEscMenu.m_sprHelpCur"] = new FlxPoint(_loc1_.x + 547,_loc1_.y + 10);
         m_vDicts[0]["GUIEscMenu.m_sprHelpLClick"] = new FlxPoint(_loc1_.x + 241,_loc1_.y + 8);
         m_vDicts[0]["GUIEscMenu.m_sprHelpL2Click"] = new FlxPoint(_loc1_.x + 235,_loc1_.y + 174);
         m_vDicts[0]["GUIEscMenu.m_sprHelpPlayer"] = new FlxPoint(_loc1_.x + 1,_loc1_.y + 261);
         m_vDicts[0]["GUIEscMenu.m_sprHelpRClick"] = new FlxPoint(_loc1_.x + 613,_loc1_.y + 200);
         m_vDicts[0]["GUIEscMenu.m_sprHelpSLClick"] = new FlxPoint(_loc1_.x + 236,_loc1_.y + 312);
         m_vDicts[0]["GUIEscMenu.m_sprHelpSpace"] = new FlxPoint(_loc1_.x + 377,_loc1_.y + 424);
         m_vDicts[0]["GUIEscMenu.m_sprHelpWASD"] = new FlxPoint(_loc1_.x + 544,_loc1_.y + 84);
         m_vDicts[0]["GUIEscMenu.m_sprInstr"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 0);
         m_vDicts[0]["GUIEscMenu.m_sprSaveGameWarning"] = new FlxPoint(_loc1_.x + 467,_loc1_.y + 16);
         m_vDicts[0]["GUIEscMenu.m_sprSaveGameWarning.MoreInfo"] = new FlxPoint(_loc1_.x + 515,_loc1_.y + 279);
         m_vDicts[0]["GUIEscMenu.m_sprSaveGameWarning.Retry"] = new FlxPoint(_loc1_.x + 585,_loc1_.y + 279);
         m_vDicts[0]["GUIEscMenu.m_sprSparkle"] = new FlxPoint(_loc1_.x + 721,_loc1_.y + 368);
         m_vDicts[0]["GUIEscMenu.m_sprTitle"] = new FlxPoint(_loc1_.x + 18,_loc1_.y + 16);
         m_vDicts[0]["GUIEscMenu.m_sprTitleGrass1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 226);
         m_vDicts[0]["GUIEscMenu.m_sprTitleIslands1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 303);
         m_vDicts[0]["GUIEscMenu.m_sprTitleMid1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 361);
         m_vDicts[0]["GUIEscMenu.m_sprTitleMtns1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 221);
         m_vDicts[0]["GUIEscMenu.m_sprTitleTrees1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 123);
         m_vDicts[0]["GUIEscMenu.m_txtConfirm"] = new FlxPoint(_loc1_.x + 325,_loc1_.y + 204);
         m_vDicts[0]["GUIEscMenu.m_txtConfirm.width"] = 150;
         m_vDicts[0]["GUIEscMenu.m_txtCopyright"] = new FlxPoint(_loc1_.x + 262,_loc1_.y + 412);
         m_vDicts[0]["GUIEscMenu.m_txtCopyright.width"] = 276;
         m_vDicts[0]["GUIEscMenu.m_txtLoadingGame"] = new FlxPoint(_loc1_.x + 336,_loc1_.y + 60);
         m_vDicts[0]["GUIEscMenu.m_txtLoadingGame.width"] = 375;
         m_vDicts[0]["GUIEscMenu.m_txtMasterVolName.width"] = 74;
         m_vDicts[0]["GUIEscMenu.m_txtFPSName"] = new FlxPoint(_loc1_.x + 514 + 26 + 16,_loc1_.y + 55 + 7 + 124);
         m_vDicts[0]["GUIEscMenu.m_txtFPSValue"] = new FlxPoint(_loc1_.x + 514 + 26 + 74 + 26,_loc1_.y + 55 + 7 + 124);
         m_vDicts[0]["GUIEscMenu.m_txtMasterVolName"] = new FlxPoint(_loc1_.x + 514 + 26 + 2,_loc1_.y + 55 + 7);
         m_vDicts[0]["GUIEscMenu.m_txtMasterVolValue"] = new FlxPoint(_loc1_.x + 514 + 26 + 74 + 26,_loc1_.y + 55 + 7);
         m_vDicts[0]["GUIEscMenu.m_txtMusicVolName"] = new FlxPoint(_loc1_.x + 514 + 26 + 6,_loc1_.y + 55 + 7 + 36);
         m_vDicts[0]["GUIEscMenu.m_txtMusicVolValue"] = new FlxPoint(_loc1_.x + 514 + 26 + 74 + 26,_loc1_.y + 55 + 7 + 36);
         m_vDicts[0]["GUIEscMenu.m_txtSoundVolName"] = new FlxPoint(_loc1_.x + 514 + 26 + 4,_loc1_.y + 55 + 7 + 72);
         m_vDicts[0]["GUIEscMenu.m_txtSoundVolValue"] = new FlxPoint(_loc1_.x + 514 + 26 + 74 + 26,_loc1_.y + 55 + 7 + 72);
         m_vDicts[0]["GUIEscMenu.m_txtVersion"] = new FlxPoint(_loc1_.x + 165,_loc1_.y + 179);
         m_vDicts[0]["GUIEscMenu.m_txtVersion.width"] = 140;
         m_vDicts[0]["GUIEscMenu.txtCreditNames"] = new FlxPoint(_loc1_.x + 337,_loc1_.y + 127);
         m_vDicts[0]["GUIEscMenu.txtCreditNames.width"] = 278;
         m_vDicts[0]["GUIEscMenu.txtCreditRoles"] = new FlxPoint(_loc1_.x + 122,_loc1_.y + 127);
         m_vDicts[0]["GUIEscMenu.txtCreditRoles.width"] = 200;
         m_vDicts[0]["GUIEscMenu.UI.Zoom"] = 1;
         m_vDicts[0]["GUIEscMenu.m_sprCredits.Instr"] = new FlxPoint(_loc1_.x + 582,_loc1_.y + 224);
         m_vDicts[0]["GUIInventory.Backpack"] = new FlxPoint(_loc1_.x + 420,_loc1_.y + 33);
         m_vDicts[0]["GUIInventory.Backpack.Cap"] = new FlxPoint(_loc1_.x + 484,_loc1_.y + 4);
         m_vDicts[0]["GUIInventory.Body"] = new FlxPoint(_loc1_.x + 231,_loc1_.y + 61);
         m_vDicts[0]["GUIInventory.Body.CapBelt"] = new FlxPoint(_loc1_.x + 273,_loc1_.y + 238);
         m_vDicts[0]["GUIInventory.Body.CapLeftShoulder"] = new FlxPoint(_loc1_.x + 373,_loc1_.y + 4);
         m_vDicts[0]["GUIInventory.Body.CapLegs"] = new FlxPoint(_loc1_.x + 273,_loc1_.y + 288);
         m_vDicts[0]["GUIInventory.Body.CapRightShoulder"] = new FlxPoint(_loc1_.x + 273,_loc1_.y + 48);
         m_vDicts[0]["GUIInventory.Body.CapTorso"] = new FlxPoint(_loc1_.x + 273,_loc1_.y + 131);
         m_vDicts[0]["GUIInventory.btnCraftAvail"] = new FlxPoint(_loc1_.x + 142,_loc1_.y + 3);
         m_vDicts[0]["GUIInventory.btnCraftConfirm"] = new FlxPoint(_loc1_.x + 537,_loc1_.y + 150);
         m_vDicts[0]["GUIInventory.btnCraftRecipes"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 3);
         m_vDicts[0]["GUIInventory.btnEncConfirm"] = new FlxPoint(_loc1_.x + 599,_loc1_.y + 217);
         m_vDicts[0]["GUIInventory.btnNextCraft"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 18);
         m_vDicts[0]["GUIInventory.btnNextYield"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 150);
         m_vDicts[0]["GUIInventory.btnPrevCraft"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 44);
         m_vDicts[0]["GUIInventory.btnPrevYield"] = new FlxPoint(_loc1_.x + 511,_loc1_.y + 150);
         m_vDicts[0]["GUIInventory.btnSkillsConfirm"] = new FlxPoint(_loc1_.x + 370,_loc1_.y + 142);
         m_vDicts[0]["GUIInventory.btnSkillsRandom"] = new FlxPoint(_loc1_.x + 370,_loc1_.y + 178);
         m_vDicts[0]["GUIInventory.grpAvailCampSlot.Cap"] = new FlxPoint(_loc1_.x + 654,_loc1_.y + 38);
         m_vDicts[0]["GUIInventory.grpAvailCraftItemsSlot.Cap"] = new FlxPoint(_loc1_.x + 70,_loc1_.y + 21);
         m_vDicts[0]["GUIInventory.grpAvailEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 189);
         m_vDicts[0]["GUIInventory.grpAvailSkillSlot.Cap"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 17);
         m_vDicts[0]["GUIInventory.grpAvailTraitSlot.Cap"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 201);
         m_vDicts[0]["GUIInventory.grpCampAlertness"] = new FlxPoint(_loc1_.x + 546,_loc1_.y + 43);
         m_vDicts[0]["GUIInventory.grpCampConcealment"] = new FlxPoint(_loc1_.x + 546,_loc1_.y + 12);
         m_vDicts[0]["GUIInventory.grpCampHealRate"] = new FlxPoint(_loc1_.x + 466,_loc1_.y + 12);
         m_vDicts[0]["GUIInventory.grpCampShelter"] = new FlxPoint(_loc1_.x + 386,_loc1_.y + 43);
         m_vDicts[0]["GUIInventory.grpCampSleepQuality"] = new FlxPoint(_loc1_.x + 466,_loc1_.y + 43);
         m_vDicts[0]["GUIInventory.grpCampSlot"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 47);
         m_vDicts[0]["GUIInventory.grpCampSlot.Cap"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 80);
         m_vDicts[0]["GUIInventory.grpCraftingIngredientsSlot.Cap"] = new FlxPoint(_loc1_.x + 391,_loc1_.y + 18);
         m_vDicts[0]["GUIInventory.grpCraftingYieldSlot.Cap"] = new FlxPoint(_loc1_.x + 391,_loc1_.y + 218);
         m_vDicts[0]["GUIInventory.grpEncounterSlot"] = new FlxPoint(_loc1_.x + 195,_loc1_.y + 91);
         m_vDicts[0]["GUIInventory.grpEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 293,_loc1_.y + 189);
         m_vDicts[0]["GUIInventory.grpEncounterSlot.zoom"] = 1;
         m_vDicts[0]["GUIInventory.grpGroundSlot.Cap"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 20);
         m_vDicts[0]["GUIInventory.grpHealthBlood"] = new FlxPoint(_loc1_.x + 597,_loc1_.y + 254);
         m_vDicts[0]["GUIInventory.grpHealthInfection"] = new FlxPoint(_loc1_.x + 597,_loc1_.y + 284);
         m_vDicts[0]["GUIInventory.grpHealthPain"] = new FlxPoint(_loc1_.x + 597,_loc1_.y + 314);
         m_vDicts[0]["GUIInventory.grpScavengeAccident"] = new FlxPoint(_loc1_.x + 158,_loc1_.y + 130);
         m_vDicts[0]["GUIInventory.grpScavengeCreature"] = new FlxPoint(_loc1_.x + 238,_loc1_.y + 130);
         m_vDicts[0]["GUIInventory.grpScavengeLoot"] = new FlxPoint(_loc1_.x + 78,_loc1_.y + 130);
         m_vDicts[0]["GUIInventory.grpScavengeLoot.size"] = 110;
         m_vDicts[0]["GUIInventory.grpVehicleSlot"] = new FlxPoint(_loc1_.x + 558,_loc1_.y + 46);
         m_vDicts[0]["GUIInventory.grpVehicleSlot.Cap"] = new FlxPoint(_loc1_.x + 277,_loc1_.y + 110);
         m_vDicts[0]["GUIInventory.HoldLeft"] = new FlxPoint(_loc1_.x + 439,_loc1_.y + 239);
         m_vDicts[0]["GUIInventory.HoldLeft.Cap"] = new FlxPoint(_loc1_.x + 484,_loc1_.y + 215);
         m_vDicts[0]["GUIInventory.HoldRight"] = new FlxPoint(_loc1_.x + 439,_loc1_.y + 134);
         m_vDicts[0]["GUIInventory.HoldRight.Cap"] = new FlxPoint(_loc1_.x + 484,_loc1_.y + 110);
         m_vDicts[0]["GUIInventory.Neck"] = new FlxPoint(_loc1_.x + 322,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.QuickRecipe.size"] = new FlxPoint(200,18);
         m_vDicts[0]["GUIInventory.Skills"] = new FlxPoint(_loc1_.x + 492,_loc1_.y + 17);
         m_vDicts[0]["GUIInventory.sprBG"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[0]["GUIInventory.sprBG.size"] = new FlxPoint(674,344);
         m_vDicts[0]["GUIInventory.sprCraftArrowDown"] = new FlxPoint(_loc1_.x + 551,_loc1_.y + 183);
         m_vDicts[0]["GUIInventory.sprCraftArrowRight"] = new FlxPoint(_loc1_.x + 319,_loc1_.y + 59);
         m_vDicts[0]["GUIInventory.sprSkillArrowRight"] = new FlxPoint(_loc1_.x + 390,_loc1_.y + 30);
         m_vDicts[0]["GUIInventory.sprTraitArrowRight"] = new FlxPoint(_loc1_.x + 390,_loc1_.y + 221);
         m_vDicts[0]["GUIInventory.sprCraftCapBG"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 18);
         m_vDicts[0]["GUIInventory.sprCraftCapBG.image"] = "GUICraftCapBG.png";
         m_vDicts[0]["GUIInventory.sprEncounter.size"] = new FlxPoint(260,180);
         m_vDicts[0]["GUIInventory.sprYieldCapBG"] = new FlxPoint(_loc1_.x + 388,_loc1_.y + 215);
         m_vDicts[0]["GUIInventory.Traits"] = new FlxPoint(_loc1_.x + 492,_loc1_.y + 201);
         m_vDicts[0]["GUIInventory.txtAvailCamp"] = new FlxPoint(_loc1_.x + 663,_loc1_.y + 14);
         m_vDicts[0]["GUIInventory.txtAvailCamp.size"] = 60;
         m_vDicts[0]["GUIInventory.txtCamp"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 23);
         m_vDicts[0]["GUIInventory.txtCamp.size"] = 130;
         m_vDicts[0]["GUIInventory.txtCondStatsWarning"] = new FlxPoint(_loc1_.x + 599,_loc1_.y + 256);
         m_vDicts[0]["GUIInventory.txtCondStatsWarning.size"] = 130;
         m_vDicts[0]["GUIInventory.txtCondTitle"] = new FlxPoint(_loc1_.x + 599,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.txtCraftMoves"] = new FlxPoint(_loc1_.x + 503,_loc1_.y + 154);
         m_vDicts[0]["GUIInventory.txtCraftMoves.size"] = 130;
         m_vDicts[0]["GUIInventory.txtCraIngredients"] = new FlxPoint(_loc1_.x + 391,_loc1_.y + 4);
         m_vDicts[0]["GUIInventory.txtCraIngredients.size"] = 220;
         m_vDicts[0]["GUIInventory.txtCraYield"] = new FlxPoint(_loc1_.x + 386,_loc1_.y + 203);
         m_vDicts[0]["GUIInventory.txtCraYield.size"] = 330;
         m_vDicts[0]["GUIInventory.txtEncAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 309);
         m_vDicts[0]["GUIInventory.txtEncAvail.size"] = 220;
         m_vDicts[0]["GUIInventory.txtEncounter"] = new FlxPoint(_loc1_.x + 326,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.txtEncounter.size"] = 409;
         m_vDicts[0]["GUIInventory.txtEncResponse"] = new FlxPoint(_loc1_.x + 516,_loc1_.y + 188);
         m_vDicts[0]["GUIInventory.txtEncResponse.size"] = 218;
         m_vDicts[0]["GUIInventory.txtEncResponseLabel"] = new FlxPoint(_loc1_.x + 294,_loc1_.y + 309);
         m_vDicts[0]["GUIInventory.txtEncResponseLabel.size"] = 220;
         m_vDicts[0]["GUIInventory.txtGroundAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.txtSkillSpace1"] = new FlxPoint(_loc1_.x + 491,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.txtSkillSpace1.size"] = 90;
         m_vDicts[0]["GUIInventory.txtSkillTotal"] = new FlxPoint(_loc1_.x + 365,_loc1_.y + 85);
         m_vDicts[0]["GUIInventory.txtSklAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 2);
         m_vDicts[0]["GUIInventory.txtSklAvail.size"] = 240;
         m_vDicts[0]["GUIInventory.txtTraitAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 185);
         m_vDicts[0]["GUIInventory.txtTraitAvail.size"] = 240;
         m_vDicts[0]["GUIInventory.txtTraitInstruct"] = new FlxPoint(_loc1_.x + 315,_loc1_.y + 270);
         m_vDicts[0]["GUIInventory.txtTraitInstruct.size"] = 173;
         m_vDicts[0]["GUIInventory.txtTraitSlot1"] = new FlxPoint(_loc1_.x + 491,_loc1_.y + 185);
         m_vDicts[0]["GUIInventory.txtTraitSlot1.size"] = 80;
         m_vDicts[0]["height"] = 450;
         m_vDicts[0]["Item.zoom"] = 1;
         m_vDicts[0]["Minimap"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[0]["Minimap.size"] = new FlxPoint(674,344);
         m_vDicts[0]["Minimap.zoom"] = 1;
         m_vDicts[0]["nBodyFontColor"] = 16777215;
         m_vDicts[0]["nBodyFontShadowColor"] = 4278190080;
         m_vDicts[0]["nBodyFontSize"] = 16;
         m_vDicts[0]["nLabelFontSize"] = 16;
         m_vDicts[0]["nTinyFontSize"] = 16;
         m_vDicts[0]["offset"] = new FlxPoint(_loc1_.x,_loc1_.y);
         m_vDicts[0]["PlayState.btnAmodeDn"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 432);
         m_vDicts[0]["PlayState.btnAmodeUp"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 409);
         m_vDicts[0]["PlayState.btnItems"] = new FlxPoint(_loc1_.x + 737,_loc1_.y + 159);
         m_vDicts[0]["PlayState.btnMainMap"] = new FlxPoint(_loc1_.x,_loc1_.y + 250);
         m_vDicts[0]["PlayState.btnWait"] = new FlxPoint(_loc1_.x + 737,_loc1_.y);
         m_vDicts[0]["PlayState.camMsg"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 344);
         m_vDicts[0]["PlayState.camMsg.btnFont"] = new FlxPoint(518,21);
         m_vDicts[0]["PlayState.camMsg.btnExpand"] = new FlxPoint(518,4);
         m_vDicts[0]["PlayState.camMsg.maxheight"] = 260;
         m_vDicts[0]["PlayState.camMsg.minheight"] = 106;
         m_vDicts[0]["PlayState.camMsg.width"] = 537;
         m_vDicts[0]["PlayState.grpAttackMode.zoom"] = 1;
         m_vDicts[0]["PlayState.grpAttackMode.ChargeHeight"] = 450;
         m_vDicts[0]["PlayState.GUIMessageWindow.m_sprBG.bigimage"] = "GUIMessageFrameBig.png";
         m_vDicts[0]["PlayState.m_txtLoadMessage"] = new FlxPoint(_loc1_.x + 200,_loc1_.y + 200);
         m_vDicts[0]["PlayState.sprAttackModeBG"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 344);
         m_vDicts[0]["PlayState.sprAttackModeBG.image"] = "AModeFrame.png";
         m_vDicts[0]["PlayState.sprAttackModeChargeOffset"] = 4;
         m_vDicts[0]["PlayState.sprCorner"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 344);
         m_vDicts[0]["PlayState.txtAttackMode"] = new FlxPoint(_loc1_.x + 624,_loc1_.y + 345);
         m_vDicts[0]["PlayState.txtAttackMode.width"] = 200;
         m_vDicts[0]["PlayState.txtAttackModeCharges"] = new FlxPoint(_loc1_.x + 576,_loc1_.y + 434);
         m_vDicts[0]["PlayState.txtAttackModeCharges.width"] = 24;
         m_vDicts[0]["PlayState.txtHexInfo"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 344);
         m_vDicts[0]["PlayState.txtHexInfo.width"] = 200;
         m_vDicts[0]["PlayState.txtMovesLeftReserve"] = new FlxPoint(-25,4);
         m_vDicts[0]["strAlignMode"] = "";
         m_vDicts[0]["strBodyFontName"] = "pixeltiny";
         m_vDicts[0]["strLabelFontName"] = "pixeltiny";
         m_vDicts[0]["strScaleMode"] = StageScaleMode.NO_SCALE;
         m_vDicts[0]["strTinyFontName"] = "pixeltiny";
         m_vDicts[0]["TextPopUp.width"] = 160;
         m_vDicts[0]["WeatherNode"] = new FlxPoint(_loc1_.x + 696,_loc1_.y);
         m_vDicts[0]["width"] = 800;
         m_vDicts[0]["zoom"] = 1;
         _loc1_ = new FlxPoint(168,0);
         m_vDicts[1]["EndState.m_btnPlay"] = new FlxPoint(_loc1_.x + 134,_loc1_.y + 301);
         m_vDicts[1]["EndState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 164,_loc1_.y + 361);
         m_vDicts[1]["EndState.sprPlayer"] = new FlxPoint(_loc1_.x + 100,_loc1_.y + 188);
         m_vDicts[1]["GameOverState.m_btnPlay"] = new FlxPoint(_loc1_.x + 118,_loc1_.y + 132);
         m_vDicts[1]["GameOverState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 138,_loc1_.y + 192);
         m_vDicts[1]["GameOverState.sprGameOver"] = new FlxPoint(_loc1_.x + 88,_loc1_.y + 28);
         m_vDicts[1]["GameOverState.sprPlayer"] = new FlxPoint(_loc1_.x + 415,_loc1_.y + 18);
         m_vDicts[1]["GameOverState.txtConds"] = new FlxPoint(_loc1_.x + 779,_loc1_.y + 10);
         m_vDicts[1]["GameOverState.txtConds.width"] = 329;
         m_vDicts[1]["GameOverState.txtLog"] = new FlxPoint(_loc1_.x + 347,_loc1_.y + 225);
         m_vDicts[1]["GameOverState.txtLog.width"] = 329;
         m_vDicts[1]["GameOverState.txtStats"] = new FlxPoint(_loc1_.x + 347,_loc1_.y + 140);
         m_vDicts[1]["GameOverState.txtStats.width"] = 329;
         m_vDicts[1]["GUIBattleScreen.btnNextEnemy"] = new FlxPoint(_loc1_.x + 782,_loc1_.y + 86);
         m_vDicts[1]["GUIBattleScreen.btnPrevEnemy"] = new FlxPoint(_loc1_.x + 674,_loc1_.y + 86);
         m_vDicts[1]["GUIBattleScreen.NumLines"] = 5;
         m_vDicts[1]["GUIBattleScreen.sprEnemy"] = new FlxPoint(_loc1_.x + 647,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprEnemyTarget"] = new FlxPoint(_loc1_.x + 955,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprEnemyMove"] = new FlxPoint(_loc1_.x + 924,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.sprEnemyNext"] = new FlxPoint(_loc1_.x + 693,_loc1_.y + -20);
         m_vDicts[1]["GUIBattleScreen.sprEnemyPanel"] = new FlxPoint(_loc1_.x + 671,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprEnemyPrev"] = new FlxPoint(_loc1_.x + 604,_loc1_.y + -20);
         m_vDicts[1]["GUIBattleScreen.sprHex"] = new FlxPoint(_loc1_.x + 438,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.sprPlayerImg"] = new FlxPoint(_loc1_.x + 25,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprPlayerTargetImg"] = new FlxPoint(_loc1_.x + 313,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprPlayerMoveImg"] = new FlxPoint(_loc1_.x + 266,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.sprPlayerPanel"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.sprPlayerPanel.image"] = "GUIBattlePanel_1024.png";
         m_vDicts[1]["GUIBattleScreen.txtEnemyFields"] = new FlxPoint(_loc1_.x + 823,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.txtEnemyFields.width"] = 116;
         m_vDicts[1]["GUIBattleScreen.txtEnemyFields2"] = new FlxPoint(_loc1_.x + 676,_loc1_.y + 165);
         m_vDicts[1]["GUIBattleScreen.txtEnemyFields2.width"] = 174;
         m_vDicts[1]["GUIBattleScreen.txtEnemyName"] = new FlxPoint(_loc1_.x + 659,_loc1_.y + 120);
         m_vDicts[1]["GUIBattleScreen.txtEnemyName.width"] = 156;
         m_vDicts[1]["GUIBattleScreen.txtEnemyVals"] = new FlxPoint(_loc1_.x + 905,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.txtEnemyVals.width"] = 120;
         m_vDicts[1]["GUIBattleScreen.txtEnemyVals2"] = new FlxPoint(_loc1_.x + 687,_loc1_.y + 188);
         m_vDicts[1]["GUIBattleScreen.txtEnemyVals2.width"] = 153;
         m_vDicts[1]["GUIBattleScreen.txtEnemyVs"] = new FlxPoint(_loc1_.x + 961,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.txtHexFields"] = new FlxPoint(_loc1_.x + 423,_loc1_.y + 174);
         m_vDicts[1]["GUIBattleScreen.txtHexFields.width"] = 166;
         m_vDicts[1]["GUIBattleScreen.txtHexVals"] = new FlxPoint(_loc1_.x + 541,_loc1_.y + 174);
         m_vDicts[1]["GUIBattleScreen.txtHexVals.width"] = 118;
         m_vDicts[1]["GUIBattleScreen.txtPlayerFields"] = new FlxPoint(_loc1_.x + 171,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.txtPlayerFields.width"] = 116;
         m_vDicts[1]["GUIBattleScreen.txtPlayerFields2"] = new FlxPoint(_loc1_.x + 71,_loc1_.y + 165);
         m_vDicts[1]["GUIBattleScreen.txtPlayerFields2.width"] = 176;
         m_vDicts[1]["GUIBattleScreen.txtPlayerName"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 120);
         m_vDicts[1]["GUIBattleScreen.txtPlayerName.width"] = 108;
         m_vDicts[1]["GUIBattleScreen.txtPlayerVals"] = new FlxPoint(_loc1_.x + 250,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.txtPlayerVals.width"] = 181;
         m_vDicts[1]["GUIBattleScreen.txtPlayerVals2"] = new FlxPoint(_loc1_.x + 71,_loc1_.y + 188);
         m_vDicts[1]["GUIBattleScreen.txtPlayerVals2.width"] = 162;
         m_vDicts[1]["GUIBattleScreen.txtPlayerVs"] = new FlxPoint(_loc1_.x + 306,_loc1_.y + 6);
         m_vDicts[1]["GUIBattleScreen.WeatherNode"] = new FlxPoint(_loc1_.x + 630,_loc1_.y + 0);
         m_vDicts[1]["GUIBattleScreen.zoom"] = 2;
         m_vDicts[1]["GUIEscMenu.m_btn1024"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 250);
         m_vDicts[1]["GUIEscMenu.m_btn1360"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 276);
         m_vDicts[1]["GUIEscMenu.m_btn1600"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 264);
         m_vDicts[1]["GUIEscMenu.m_btn2400"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 316);
         m_vDicts[1]["GUIEscMenu.m_btn800"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 224);
         m_vDicts[1]["GUIEscMenu.m_btnAUTO"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 198);
         m_vDicts[1]["GUIEscMenu.m_btnAutosave"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 450);
         m_vDicts[1]["GUIEscMenu.m_btnBBG"] = new FlxPoint(_loc1_.x + 831,_loc1_.y + 667);
         m_vDicts[1]["GUIEscMenu.m_btnCancel"] = new FlxPoint(_loc1_.x + 686,_loc1_.y + 386);
         m_vDicts[1]["GUIEscMenu.m_btnCredits"] = new FlxPoint(_loc1_.x + 449,_loc1_.y + 410);
         m_vDicts[1]["GUIEscMenu.m_btnExit"] = new FlxPoint(_loc1_.x + 417,_loc1_.y + 136);
         m_vDicts[1]["GUIEscMenu.m_btnFilter"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 476);
         m_vDicts[1]["GUIEscMenu.m_btnFPSDn"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 198 + 124);
         m_vDicts[1]["GUIEscMenu.m_btnFPSUp"] = new FlxPoint(_loc1_.x + 605 + 74 + 26,_loc1_.y + 198 + 124);
         m_vDicts[1]["GUIEscMenu.m_btnFullscreen"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 450);
         m_vDicts[1]["GUIEscMenu.m_btnGreenlight"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 752);
         m_vDicts[1]["GUIEscMenu.m_btnInstr"] = new FlxPoint(_loc1_.x + 449,_loc1_.y + 384);
         m_vDicts[1]["GUIEscMenu.m_btnLoad"] = new FlxPoint(_loc1_.x + 417,_loc1_.y + 16);
         m_vDicts[1]["GUIEscMenu.m_btnMain"] = new FlxPoint(_loc1_.x + 55,_loc1_.y + 164);
         m_vDicts[1]["GUIEscMenu.m_btnManual"] = new FlxPoint(_loc1_.x + 27,_loc1_.y + 28);
         m_vDicts[1]["GUIEscMenu.m_btnMasterDn"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 198);
         m_vDicts[1]["GUIEscMenu.m_btnMasterUp"] = new FlxPoint(_loc1_.x + 605 + 74 + 26,_loc1_.y + 198);
         m_vDicts[1]["GUIEscMenu.m_btnMusicDn"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 198 + 36);
         m_vDicts[1]["GUIEscMenu.m_btnMusicUp"] = new FlxPoint(_loc1_.x + 605 + 74 + 26,_loc1_.y + 198 + 36);
         m_vDicts[1]["GUIEscMenu.m_btnMute"] = new FlxPoint(_loc1_.x + 927,_loc1_.y + 16);
         m_vDicts[1]["GUIEscMenu.m_btnOK"] = new FlxPoint(_loc1_.x + 608,_loc1_.y + 386);
         m_vDicts[1]["GUIEscMenu.m_btnOptions"] = new FlxPoint(_loc1_.x + 449,_loc1_.y + 358);
         m_vDicts[1]["GUIEscMenu.m_btnPlay"] = new FlxPoint(_loc1_.x + 417,_loc1_.y + 92);
         m_vDicts[1]["GUIEscMenu.m_btnReset"] = new FlxPoint(_loc1_.x + 449,_loc1_.y + 384);
         m_vDicts[1]["GUIEscMenu.m_btnSoundDn"] = new FlxPoint(_loc1_.x + 605,_loc1_.y + 198 + 72);
         m_vDicts[1]["GUIEscMenu.m_btnSoundUp"] = new FlxPoint(_loc1_.x + 605 + 74 + 26,_loc1_.y + 198 + 72);
         m_vDicts[1]["GUIEscMenu.m_btnStretch"] = new FlxPoint(_loc1_.x + 428,_loc1_.y + 502);
         m_vDicts[1]["GUIEscMenu.m_btnTerEdit"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 298);
         m_vDicts[1]["GUIEscMenu.m_btnWiki"] = new FlxPoint(_loc1_.x + 27,_loc1_.y + 93);
         m_vDicts[1]["GUIEscMenu.m_btnZomboid"] = new FlxPoint(_loc1_.x + 717,_loc1_.y + 752);
         m_vDicts[1]["GUIEscMenu.m_sprBugsBG"] = new FlxPoint(_loc1_.x + 140,_loc1_.y + 752);
         m_vDicts[1]["GUIEscMenu.m_sprCredits"] = new FlxPoint(_loc1_.x + 512,_loc1_.y + 384);
         m_vDicts[1]["GUIEscMenu.m_sprDialogBG"] = new FlxPoint(_loc1_.x + 604,_loc1_.y + 346);
         m_vDicts[1]["GUIEscMenu.m_sprDialogBG.size"] = new FlxPoint(150,70);
         m_vDicts[1]["GUIEscMenu.m_sprHelpCur"] = new FlxPoint(_loc1_.x + 777,_loc1_.y + 10);
         m_vDicts[1]["GUIEscMenu.m_sprHelpLClick"] = new FlxPoint(_loc1_.x + 241,_loc1_.y + 8);
         m_vDicts[1]["GUIEscMenu.m_sprHelpL2Click"] = new FlxPoint(_loc1_.x + 235,_loc1_.y + 274);
         m_vDicts[1]["GUIEscMenu.m_sprHelpPlayer"] = new FlxPoint(_loc1_.x + 1,_loc1_.y + 579);
         m_vDicts[1]["GUIEscMenu.m_sprHelpRClick"] = new FlxPoint(_loc1_.x + 843,_loc1_.y + 400);
         m_vDicts[1]["GUIEscMenu.m_sprHelpSLClick"] = new FlxPoint(_loc1_.x + 236,_loc1_.y + 512);
         m_vDicts[1]["GUIEscMenu.m_sprHelpSpace"] = new FlxPoint(_loc1_.x + 489,_loc1_.y + 730);
         m_vDicts[1]["GUIEscMenu.m_sprHelpWASD"] = new FlxPoint(_loc1_.x + 774,_loc1_.y + 204);
         m_vDicts[1]["GUIEscMenu.m_sprInstr"] = new FlxPoint(_loc1_.x - 120,_loc1_.y + -62);
         m_vDicts[1]["GUIEscMenu.m_sprSaveGameWarning"] = new FlxPoint(_loc1_.x + 569,_loc1_.y + 16);
         m_vDicts[1]["GUIEscMenu.m_sprSaveGameWarning.MoreInfo"] = new FlxPoint(_loc1_.x + 617,_loc1_.y + 279);
         m_vDicts[1]["GUIEscMenu.m_sprSaveGameWarning.Retry"] = new FlxPoint(_loc1_.x + 683,_loc1_.y + 279);
         m_vDicts[1]["GUIEscMenu.m_sprSparkle"] = new FlxPoint(_loc1_.x + 947,_loc1_.y + 688);
         m_vDicts[1]["GUIEscMenu.m_sprTitle"] = new FlxPoint(_loc1_.x + 18,_loc1_.y + 16);
         m_vDicts[1]["GUIEscMenu.m_sprTitleGrass1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 226 + 109);
         m_vDicts[1]["GUIEscMenu.m_sprTitleIslands1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 303 + 109);
         m_vDicts[1]["GUIEscMenu.m_sprTitleMid1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 361 + 109);
         m_vDicts[1]["GUIEscMenu.m_sprTitleMtns1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 221 + 109);
         m_vDicts[1]["GUIEscMenu.m_sprTitleTrees1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 123 + 109);
         m_vDicts[1]["GUIEscMenu.m_txtConfirm"] = new FlxPoint(_loc1_.x + 604,_loc1_.y + 359);
         m_vDicts[1]["GUIEscMenu.m_txtConfirm.width"] = 150;
         m_vDicts[1]["GUIEscMenu.m_txtCopyright"] = new FlxPoint(_loc1_.x + 236,_loc1_.y + 714);
         m_vDicts[1]["GUIEscMenu.m_txtCopyright.width"] = 552;
         m_vDicts[1]["GUIEscMenu.m_txtLoadingGame"] = new FlxPoint(_loc1_.x + 385,_loc1_.y + 64);
         m_vDicts[1]["GUIEscMenu.m_txtLoadingGame.width"] = 550;
         m_vDicts[1]["GUIEscMenu.m_txtMasterVolName.width"] = 74;
         m_vDicts[1]["GUIEscMenu.m_txtFPSName"] = new FlxPoint(_loc1_.x + 605 + 26 + 16,_loc1_.y + 198 + 7 + 124);
         m_vDicts[1]["GUIEscMenu.m_txtFPSValue"] = new FlxPoint(_loc1_.x + 605 + 26 + 74 + 26,_loc1_.y + 198 + 7 + 124);
         m_vDicts[1]["GUIEscMenu.m_txtMasterVolName"] = new FlxPoint(_loc1_.x + 605 + 26 + 2,_loc1_.y + 198 + 7);
         m_vDicts[1]["GUIEscMenu.m_txtMasterVolValue"] = new FlxPoint(_loc1_.x + 605 + 26 + 74 + 26,_loc1_.y + 198 + 7);
         m_vDicts[1]["GUIEscMenu.m_txtMusicVolName"] = new FlxPoint(_loc1_.x + 605 + 26 + 6,_loc1_.y + 198 + 7 + 36);
         m_vDicts[1]["GUIEscMenu.m_txtMusicVolValue"] = new FlxPoint(_loc1_.x + 605 + 26 + 74 + 26,_loc1_.y + 198 + 7 + 36);
         m_vDicts[1]["GUIEscMenu.m_txtSoundVolName"] = new FlxPoint(_loc1_.x + 605 + 26 + 4,_loc1_.y + 198 + 7 + 72);
         m_vDicts[1]["GUIEscMenu.m_txtSoundVolValue"] = new FlxPoint(_loc1_.x + 605 + 26 + 74 + 26,_loc1_.y + 198 + 7 + 72);
         m_vDicts[1]["GUIEscMenu.m_txtVersion"] = new FlxPoint(_loc1_.x + 12,_loc1_.y + 187);
         m_vDicts[1]["GUIEscMenu.m_txtVersion.width"] = 280;
         m_vDicts[1]["GUIEscMenu.txtCreditNames"] = new FlxPoint(_loc1_.x + 455,_loc1_.y + 90);
         m_vDicts[1]["GUIEscMenu.txtCreditNames.width"] = 544;
         m_vDicts[1]["GUIEscMenu.txtCreditRoles"] = new FlxPoint(_loc1_.x + 121,_loc1_.y + 90);
         m_vDicts[1]["GUIEscMenu.txtCreditRoles.width"] = 300;
         m_vDicts[1]["GUIEscMenu.UI.Zoom"] = 1;
         m_vDicts[1]["GUIEscMenu.m_sprCredits.Instr"] = new FlxPoint(_loc1_.x + 690,_loc1_.y + 384);
         m_vDicts[1]["GUIInventory.Backpack"] = new FlxPoint(_loc1_.x + 450,_loc1_.y + 33);
         m_vDicts[1]["GUIInventory.Backpack.Cap"] = new FlxPoint(_loc1_.x + 524,_loc1_.y + 4);
         m_vDicts[1]["GUIInventory.Body"] = new FlxPoint(_loc1_.x + 251,_loc1_.y + 61);
         m_vDicts[1]["GUIInventory.Body.CapBelt"] = new FlxPoint(_loc1_.x + 283,_loc1_.y + 238);
         m_vDicts[1]["GUIInventory.Body.CapLeftShoulder"] = new FlxPoint(_loc1_.x + 393,_loc1_.y + 4);
         m_vDicts[1]["GUIInventory.Body.CapLegs"] = new FlxPoint(_loc1_.x + 283,_loc1_.y + 288);
         m_vDicts[1]["GUIInventory.Body.CapRightShoulder"] = new FlxPoint(_loc1_.x + 283,_loc1_.y + 48);
         m_vDicts[1]["GUIInventory.Body.CapTorso"] = new FlxPoint(_loc1_.x + 283,_loc1_.y + 131);
         m_vDicts[1]["GUIInventory.btnCraftAvail"] = new FlxPoint(_loc1_.x + 142,_loc1_.y + 3);
         m_vDicts[1]["GUIInventory.btnCraftConfirm"] = new FlxPoint(_loc1_.x + 737,_loc1_.y + 209);
         m_vDicts[1]["GUIInventory.btnCraftRecipes"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 3);
         m_vDicts[1]["GUIInventory.btnEncConfirm"] = new FlxPoint(_loc1_.x + 599,_loc1_.y + 217);
         m_vDicts[1]["GUIInventory.btnNextCraft"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 18);
         m_vDicts[1]["GUIInventory.btnNextYield"] = new FlxPoint(_loc1_.x + 800,_loc1_.y + 209);
         m_vDicts[1]["GUIInventory.btnPrevCraft"] = new FlxPoint(_loc1_.x + 272,_loc1_.y + 44);
         m_vDicts[1]["GUIInventory.btnPrevYield"] = new FlxPoint(_loc1_.x + 711,_loc1_.y + 209);
         m_vDicts[1]["GUIInventory.btnSkillsConfirm"] = new FlxPoint(_loc1_.x + 518,_loc1_.y + 187);
         m_vDicts[1]["GUIInventory.btnSkillsRandom"] = new FlxPoint(_loc1_.x + 518,_loc1_.y + 223);
         m_vDicts[1]["GUIInventory.grpAvailCampSlot.Cap"] = new FlxPoint(_loc1_.x + 654,_loc1_.y + 78);
         m_vDicts[1]["GUIInventory.grpAvailCraftItemsSlot.Cap"] = new FlxPoint(_loc1_.x + 70,_loc1_.y + 21);
         m_vDicts[1]["GUIInventory.grpAvailEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 345);
         m_vDicts[1]["GUIInventory.grpAvailSkillSlot.Cap"] = new FlxPoint(_loc1_.x + 145,_loc1_.y + 47);
         m_vDicts[1]["GUIInventory.grpAvailTraitSlot.Cap"] = new FlxPoint(_loc1_.x + 145,_loc1_.y + 341);
         m_vDicts[1]["GUIInventory.grpCampAlertness"] = new FlxPoint(_loc1_.x + 546,_loc1_.y + 43);
         m_vDicts[1]["GUIInventory.grpCampConcealment"] = new FlxPoint(_loc1_.x + 546,_loc1_.y + 12);
         m_vDicts[1]["GUIInventory.grpCampHealRate"] = new FlxPoint(_loc1_.x + 466,_loc1_.y + 12);
         m_vDicts[1]["GUIInventory.grpCampShelter"] = new FlxPoint(_loc1_.x + 386,_loc1_.y + 43);
         m_vDicts[1]["GUIInventory.grpCampSleepQuality"] = new FlxPoint(_loc1_.x + 466,_loc1_.y + 43);
         m_vDicts[1]["GUIInventory.grpCampSlot"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 47);
         m_vDicts[1]["GUIInventory.grpCampSlot.Cap"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 80);
         m_vDicts[1]["GUIInventory.grpCraftingIngredientsSlot.Cap"] = new FlxPoint(_loc1_.x + 591,_loc1_.y + 28);
         m_vDicts[1]["GUIInventory.grpCraftingYieldSlot.Cap"] = new FlxPoint(_loc1_.x + 591,_loc1_.y + 358);
         m_vDicts[1]["GUIInventory.grpEncounterSlot"] = new FlxPoint(_loc1_.x + 195,_loc1_.y + 91);
         m_vDicts[1]["GUIInventory.grpEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 293,_loc1_.y + 345);
         m_vDicts[1]["GUIInventory.grpEncounterSlot.zoom"] = 1;
         m_vDicts[1]["GUIInventory.grpGroundSlot.Cap"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 50);
         m_vDicts[1]["GUIInventory.grpHealthBlood"] = new FlxPoint(_loc1_.x + 68,_loc1_.y + 344);
         m_vDicts[1]["GUIInventory.grpHealthInfection"] = new FlxPoint(_loc1_.x + 68,_loc1_.y + 374);
         m_vDicts[1]["GUIInventory.grpHealthPain"] = new FlxPoint(_loc1_.x + 68,_loc1_.y + 404);
         m_vDicts[1]["GUIInventory.grpScavengeAccident"] = new FlxPoint(_loc1_.x + 158,_loc1_.y + 130);
         m_vDicts[1]["GUIInventory.grpScavengeCreature"] = new FlxPoint(_loc1_.x + 238,_loc1_.y + 130);
         m_vDicts[1]["GUIInventory.grpScavengeLoot"] = new FlxPoint(_loc1_.x + 78,_loc1_.y + 130);
         m_vDicts[1]["GUIInventory.grpScavengeLoot.size"] = 110;
         m_vDicts[1]["GUIInventory.grpVehicleSlot"] = new FlxPoint(_loc1_.x + 558,_loc1_.y + 96);
         m_vDicts[1]["GUIInventory.grpVehicleSlot.Cap"] = new FlxPoint(_loc1_.x + 277,_loc1_.y + 50);
         m_vDicts[1]["GUIInventory.HoldLeft"] = new FlxPoint(_loc1_.x + 469,_loc1_.y + 239);
         m_vDicts[1]["GUIInventory.HoldLeft.Cap"] = new FlxPoint(_loc1_.x + 524,_loc1_.y + 215);
         m_vDicts[1]["GUIInventory.HoldRight"] = new FlxPoint(_loc1_.x + 469,_loc1_.y + 134);
         m_vDicts[1]["GUIInventory.HoldRight.Cap"] = new FlxPoint(_loc1_.x + 524,_loc1_.y + 110);
         m_vDicts[1]["GUIInventory.Neck"] = new FlxPoint(_loc1_.x + 342,_loc1_.y + 2);
         m_vDicts[1]["GUIInventory.QuickRecipe.size"] = new FlxPoint(200,28);
         m_vDicts[1]["GUIInventory.Skills"] = new FlxPoint(_loc1_.x + 701,_loc1_.y + 47);
         m_vDicts[1]["GUIInventory.sprBG"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[1]["GUIInventory.sprBG.size"] = new FlxPoint(969,482);
         m_vDicts[1]["GUIInventory.sprCraftArrowDown"] = new FlxPoint(_loc1_.x + 751,_loc1_.y + 242);
         m_vDicts[1]["GUIInventory.sprCraftArrowRight"] = new FlxPoint(_loc1_.x + 519,_loc1_.y + 59);
         m_vDicts[1]["GUIInventory.sprSkillArrowRight"] = new FlxPoint(_loc1_.x + 540,_loc1_.y + 61);
         m_vDicts[1]["GUIInventory.sprTraitArrowRight"] = new FlxPoint(_loc1_.x + 540,_loc1_.y + 346);
         m_vDicts[1]["GUIInventory.sprCraftCapBG"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 18);
         m_vDicts[1]["GUIInventory.sprCraftCapBG.image"] = "GUICraftCapBG_1024.png";
         m_vDicts[1]["GUIInventory.sprEncounter.size"] = new FlxPoint(260,180);
         m_vDicts[1]["GUIInventory.sprYieldCapBG"] = new FlxPoint(_loc1_.x + 588,_loc1_.y + 355);
         m_vDicts[1]["GUIInventory.Traits"] = new FlxPoint(_loc1_.x + 701,_loc1_.y + 341);
         m_vDicts[1]["GUIInventory.txtAvailCamp"] = new FlxPoint(_loc1_.x + 653,_loc1_.y + 14);
         m_vDicts[1]["GUIInventory.txtAvailCamp.size"] = 120;
         m_vDicts[1]["GUIInventory.txtCamp"] = new FlxPoint(_loc1_.x + 287,_loc1_.y + 2);
         m_vDicts[1]["GUIInventory.txtCamp.size"] = 170;
         m_vDicts[1]["GUIInventory.txtCondStatsWarning"] = new FlxPoint(_loc1_.x + 68,_loc1_.y + 344);
         m_vDicts[1]["GUIInventory.txtCondStatsWarning.size"] = 375;
         m_vDicts[1]["GUIInventory.txtCondTitle"] = new FlxPoint(_loc1_.x + 639,_loc1_.y + 2);
         m_vDicts[1]["GUIInventory.txtCraftMoves"] = new FlxPoint(_loc1_.x + 586,_loc1_.y + 183);
         m_vDicts[1]["GUIInventory.txtCraftMoves.size"] = 332;
         m_vDicts[1]["GUIInventory.txtCraIngredients"] = new FlxPoint(_loc1_.x + 591,_loc1_.y + 4);
         m_vDicts[1]["GUIInventory.txtCraIngredients.size"] = 320;
         m_vDicts[1]["GUIInventory.txtCraYield"] = new FlxPoint(_loc1_.x + 586,_loc1_.y + 307);
         m_vDicts[1]["GUIInventory.txtCraYield.size"] = 425;
         m_vDicts[1]["GUIInventory.txtEncAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 465);
         m_vDicts[1]["GUIInventory.txtEncAvail.size"] = 220;
         m_vDicts[1]["GUIInventory.txtEncounter"] = new FlxPoint(_loc1_.x + 331,_loc1_.y + 2);
         m_vDicts[1]["GUIInventory.txtEncounter.size"] = 694;
         m_vDicts[1]["GUIInventory.txtEncResponse"] = new FlxPoint(_loc1_.x + 516,_loc1_.y + 345);
         m_vDicts[1]["GUIInventory.txtEncResponse.size"] = 504;
         m_vDicts[1]["GUIInventory.txtEncResponseLabel"] = new FlxPoint(_loc1_.x + 294,_loc1_.y + 465);
         m_vDicts[1]["GUIInventory.txtEncResponseLabel.size"] = 220;
         m_vDicts[1]["GUIInventory.txtGroundAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 17);
         m_vDicts[1]["GUIInventory.txtSkillSpace1"] = new FlxPoint(_loc1_.x + 701,_loc1_.y + 17);
         m_vDicts[1]["GUIInventory.txtSkillSpace1.size"] = 260;
         m_vDicts[1]["GUIInventory.txtSkillTotal"] = new FlxPoint(_loc1_.x + 483,_loc1_.y + 109);
         m_vDicts[1]["GUIInventory.txtSklAvail"] = new FlxPoint(_loc1_.x + 143,_loc1_.y + 17);
         m_vDicts[1]["GUIInventory.txtSklAvail.size"] = 300;
         m_vDicts[1]["GUIInventory.txtTraitAvail"] = new FlxPoint(_loc1_.x + 143,_loc1_.y + 310);
         m_vDicts[1]["GUIInventory.txtTraitAvail.size"] = 300;
         m_vDicts[1]["GUIInventory.txtTraitInstruct"] = new FlxPoint(_loc1_.x + 402,_loc1_.y + 400);
         m_vDicts[1]["GUIInventory.txtTraitInstruct.size"] = 320;
         m_vDicts[1]["GUIInventory.txtTraitSlot1"] = new FlxPoint(_loc1_.x + 701,_loc1_.y + 310);
         m_vDicts[1]["GUIInventory.txtTraitSlot1.size"] = 260;
         m_vDicts[1]["height"] = 768;
         m_vDicts[1]["Item.zoom"] = 1;
         m_vDicts[1]["Minimap"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[1]["Minimap.size"] = new FlxPoint(969,482);
         m_vDicts[1]["Minimap.zoom"] = 2;
         m_vDicts[1]["nBodyFontColor"] = 16777215;
         m_vDicts[1]["nBodyFontShadowColor"] = 4278190080;
         m_vDicts[1]["nBodyFontSize"] = 32;
         m_vDicts[1]["nLabelFontSize"] = 16;
         m_vDicts[1]["nTinyFontSize"] = 16;
         m_vDicts[1]["offset"] = new FlxPoint(_loc1_.x,_loc1_.y);
         m_vDicts[1]["PlayState.btnAmodeDn"] = new FlxPoint(_loc1_.x + 824,_loc1_.y + 570);
         m_vDicts[1]["PlayState.btnAmodeUp"] = new FlxPoint(_loc1_.x + 824,_loc1_.y + 547);
         m_vDicts[1]["PlayState.btnItems"] = new FlxPoint(_loc1_.x,_loc1_.y + 610);
         m_vDicts[1]["PlayState.btnMainMap"] = new FlxPoint(_loc1_.x,_loc1_.y + 410);
         m_vDicts[1]["PlayState.btnWait"] = new FlxPoint(_loc1_.x,_loc1_.y + 250);
         m_vDicts[1]["PlayState.camMsg"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 482);
         m_vDicts[1]["PlayState.camMsg.btnFont"] = new FlxPoint(740,21);
         m_vDicts[1]["PlayState.camMsg.btnExpand"] = new FlxPoint(740,4);
         m_vDicts[1]["PlayState.camMsg.maxheight"] = 486;
         m_vDicts[1]["PlayState.camMsg.minheight"] = 286;
         m_vDicts[1]["PlayState.camMsg.width"] = 761;
         m_vDicts[1]["PlayState.grpAttackMode.zoom"] = 1;
         m_vDicts[1]["PlayState.grpAttackMode.ChargeHeight"] = 589;
         m_vDicts[1]["PlayState.GUIMessageWindow.m_sprBG.bigimage"] = "GUIMessageFrameBig_1024x768.png";
         m_vDicts[1]["PlayState.m_txtLoadMessage"] = new FlxPoint(_loc1_.x + 350,_loc1_.y + 350);
         m_vDicts[1]["PlayState.sprAttackModeBG"] = new FlxPoint(_loc1_.x + 824,_loc1_.y + 482);
         m_vDicts[1]["PlayState.sprAttackModeBG.image"] = "AModeFrame.png";
         m_vDicts[1]["PlayState.sprAttackModeChargeOffset"] = 4;
         m_vDicts[1]["PlayState.sprCorner"] = new FlxPoint(_loc1_.x + 824,_loc1_.y + 768 - 180);
         m_vDicts[1]["PlayState.txtAttackMode"] = new FlxPoint(_loc1_.x + 848,_loc1_.y + 483);
         m_vDicts[1]["PlayState.txtAttackMode.width"] = 200;
         m_vDicts[1]["PlayState.txtAttackModeCharges"] = new FlxPoint(_loc1_.x + 800,_loc1_.y + 572);
         m_vDicts[1]["PlayState.txtAttackModeCharges.width"] = 24;
         m_vDicts[1]["PlayState.txtHexInfo"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 482);
         m_vDicts[1]["PlayState.txtHexInfo.width"] = 400;
         m_vDicts[1]["PlayState.txtMovesLeftReserve"] = new FlxPoint(63,4);
         m_vDicts[1]["strAlignMode"] = "";
         m_vDicts[1]["strBodyFontName"] = "pixelmid";
         m_vDicts[1]["strLabelFontName"] = "pixeltiny";
         m_vDicts[1]["strScaleMode"] = StageScaleMode.NO_SCALE;
         m_vDicts[1]["strTinyFontName"] = "pixeltiny";
         m_vDicts[1]["TextPopUp.width"] = 320;
         m_vDicts[1]["WeatherNode"] = new FlxPoint(_loc1_.x + 983,_loc1_.y);
         m_vDicts[1]["width"] = 1024;
         m_vDicts[1]["zoom"] = 1;
         _loc1_ = new FlxPoint(0,0);
         m_vDicts[2]["EndState.m_btnPlay"] = new FlxPoint(_loc1_.x + 200,_loc1_.y + 492);
         m_vDicts[2]["EndState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 263,_loc1_.y + 582);
         m_vDicts[2]["EndState.sprPlayer"] = new FlxPoint(_loc1_.x + 225,_loc1_.y + 376);
         m_vDicts[2]["GameOverState.m_btnPlay"] = new FlxPoint(_loc1_.x + 120,_loc1_.y + 208);
         m_vDicts[2]["GameOverState.m_btnClipboard"] = new FlxPoint(_loc1_.x + 163,_loc1_.y + 328);
         m_vDicts[2]["GameOverState.sprGameOver"] = new FlxPoint(_loc1_.x + 60,_loc1_.y + 26);
         m_vDicts[2]["GameOverState.sprPlayer"] = new FlxPoint(_loc1_.x + 565,_loc1_.y + 36);
         m_vDicts[2]["GameOverState.txtConds"] = new FlxPoint(_loc1_.x + 913,_loc1_.y + 20);
         m_vDicts[2]["GameOverState.txtConds.width"] = 441;
         m_vDicts[2]["GameOverState.txtLog"] = new FlxPoint(_loc1_.x + 459,_loc1_.y + 384);
         m_vDicts[2]["GameOverState.txtLog.width"] = 441;
         m_vDicts[2]["GameOverState.txtStats"] = new FlxPoint(_loc1_.x + 459,_loc1_.y + 164);
         m_vDicts[2]["GameOverState.txtStats.width"] = 441;
         m_vDicts[2]["GUIBattleScreen.btnNextEnemy"] = new FlxPoint(_loc1_.x + 963,_loc1_.y + 156);
         m_vDicts[2]["GUIBattleScreen.btnPrevEnemy"] = new FlxPoint(_loc1_.x + 933,_loc1_.y + 156);
         m_vDicts[2]["GUIBattleScreen.NumLines"] = 5;
         m_vDicts[2]["GUIBattleScreen.sprEnemy"] = new FlxPoint(_loc1_.x + 867,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprEnemyTarget"] = new FlxPoint(_loc1_.x + 1242,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprEnemyMove"] = new FlxPoint(_loc1_.x + 1159,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.sprEnemyNext"] = new FlxPoint(_loc1_.x + 913,_loc1_.y + -20);
         m_vDicts[2]["GUIBattleScreen.sprEnemyPanel"] = new FlxPoint(_loc1_.x + 889,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprEnemyPrev"] = new FlxPoint(_loc1_.x + 824,_loc1_.y + -20);
         m_vDicts[2]["GUIBattleScreen.sprHex"] = new FlxPoint(_loc1_.x + 635,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.sprPlayerImg"] = new FlxPoint(_loc1_.x + 25,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprPlayerTargetImg"] = new FlxPoint(_loc1_.x + 390,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprPlayerMoveImg"] = new FlxPoint(_loc1_.x + 297,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.sprPlayerPanel"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.sprPlayerPanel.image"] = "GUIBattlePanel_1360.png";
         m_vDicts[2]["GUIBattleScreen.txtEnemyFields"] = new FlxPoint(_loc1_.x + 1043,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.txtEnemyFields.width"] = 116;
         m_vDicts[2]["GUIBattleScreen.txtEnemyFields2"] = new FlxPoint(_loc1_.x + 907,_loc1_.y + 204);
         m_vDicts[2]["GUIBattleScreen.txtEnemyFields2.width"] = 224;
         m_vDicts[2]["GUIBattleScreen.txtEnemyName"] = new FlxPoint(_loc1_.x + 879,_loc1_.y + 120);
         m_vDicts[2]["GUIBattleScreen.txtEnemyName.width"] = 156;
         m_vDicts[2]["GUIBattleScreen.txtEnemyVals"] = new FlxPoint(_loc1_.x + 1163,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.txtEnemyVals.width"] = 196;
         m_vDicts[2]["GUIBattleScreen.txtEnemyVals2"] = new FlxPoint(_loc1_.x + 1027,_loc1_.y + 204);
         m_vDicts[2]["GUIBattleScreen.txtEnemyVals2.width"] = 224;
         m_vDicts[2]["GUIBattleScreen.txtEnemyVs"] = new FlxPoint(_loc1_.x + 1224,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.txtHexFields"] = new FlxPoint(_loc1_.x + 595,_loc1_.y + 174);
         m_vDicts[2]["GUIBattleScreen.txtHexFields.width"] = 166;
         m_vDicts[2]["GUIBattleScreen.txtHexVals"] = new FlxPoint(_loc1_.x + 713,_loc1_.y + 174);
         m_vDicts[2]["GUIBattleScreen.txtHexVals.width"] = 118;
         m_vDicts[2]["GUIBattleScreen.txtPlayerFields"] = new FlxPoint(_loc1_.x + 171,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.txtPlayerFields.width"] = 116;
         m_vDicts[2]["GUIBattleScreen.txtPlayerFields2"] = new FlxPoint(_loc1_.x + 81,_loc1_.y + 204);
         m_vDicts[2]["GUIBattleScreen.txtPlayerFields2.width"] = 244;
         m_vDicts[2]["GUIBattleScreen.txtPlayerName"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 120);
         m_vDicts[2]["GUIBattleScreen.txtPlayerName.width"] = 108;
         m_vDicts[2]["GUIBattleScreen.txtPlayerVals"] = new FlxPoint(_loc1_.x + 301,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.txtPlayerVals.width"] = 244;
         m_vDicts[2]["GUIBattleScreen.txtPlayerVals2"] = new FlxPoint(_loc1_.x + 203,_loc1_.y + 204);
         m_vDicts[2]["GUIBattleScreen.txtPlayerVals2.width"] = 244;
         m_vDicts[2]["GUIBattleScreen.txtPlayerVs"] = new FlxPoint(_loc1_.x + 387,_loc1_.y + 6);
         m_vDicts[2]["GUIBattleScreen.WeatherNode"] = new FlxPoint(_loc1_.x + 807,_loc1_.y + 0);
         m_vDicts[2]["GUIBattleScreen.zoom"] = 2;
         m_vDicts[2]["GUIEscMenu.m_btn1024"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 72 + 104);
         m_vDicts[2]["GUIEscMenu.m_btn1360"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 72 + 156);
         m_vDicts[2]["GUIEscMenu.m_btn1600"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 264);
         m_vDicts[2]["GUIEscMenu.m_btn2400"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 316);
         m_vDicts[2]["GUIEscMenu.m_btn800"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 72 + 52);
         m_vDicts[2]["GUIEscMenu.m_btnAUTO"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 72);
         m_vDicts[2]["GUIEscMenu.m_btnAutosave"] = new FlxPoint(_loc1_.x + 842,_loc1_.y + 536);
         m_vDicts[2]["GUIEscMenu.m_btnBBG"] = new FlxPoint(_loc1_.x + 970,_loc1_.y + 561);
         m_vDicts[2]["GUIEscMenu.m_btnCancel"] = new FlxPoint(_loc1_.x + 686,_loc1_.y + 386);
         m_vDicts[2]["GUIEscMenu.m_btnCredits"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 462);
         m_vDicts[2]["GUIEscMenu.m_btnExit"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 250);
         m_vDicts[2]["GUIEscMenu.m_btnFilter"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 536 + 52);
         m_vDicts[2]["GUIEscMenu.m_btnFPSDn"] = new FlxPoint(_loc1_.x + 842,_loc1_.y + 72 + 260);
         m_vDicts[2]["GUIEscMenu.m_btnFPSUp"] = new FlxPoint(_loc1_.x + 842 + 74 + 52,_loc1_.y + 72 + 260);
         m_vDicts[2]["GUIEscMenu.m_btnFullscreen"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 536);
         m_vDicts[2]["GUIEscMenu.m_btnGreenlight"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 732);
         m_vDicts[2]["GUIEscMenu.m_btnInstr"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 410);
         m_vDicts[2]["GUIEscMenu.m_btnLoad"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 16);
         m_vDicts[2]["GUIEscMenu.m_btnMain"] = new FlxPoint(_loc1_.x + 70,_loc1_.y + 205);
         m_vDicts[2]["GUIEscMenu.m_btnManual"] = new FlxPoint(_loc1_.x + 10,_loc1_.y + 12);
         m_vDicts[2]["GUIEscMenu.m_btnMasterDn"] = new FlxPoint(_loc1_.x + 842,_loc1_.y + 72);
         m_vDicts[2]["GUIEscMenu.m_btnMasterUp"] = new FlxPoint(_loc1_.x + 842 + 74 + 52,_loc1_.y + 72);
         m_vDicts[2]["GUIEscMenu.m_btnMusicDn"] = new FlxPoint(_loc1_.x + 842,_loc1_.y + 72 + 52);
         m_vDicts[2]["GUIEscMenu.m_btnMusicUp"] = new FlxPoint(_loc1_.x + 842 + 74 + 52,_loc1_.y + 72 + 52);
         m_vDicts[2]["GUIEscMenu.m_btnMute"] = new FlxPoint(_loc1_.x + 1180,_loc1_.y + 16);
         m_vDicts[2]["GUIEscMenu.m_btnOK"] = new FlxPoint(_loc1_.x + 608,_loc1_.y + 386);
         m_vDicts[2]["GUIEscMenu.m_btnOptions"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 358);
         m_vDicts[2]["GUIEscMenu.m_btnPlay"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 146);
         m_vDicts[2]["GUIEscMenu.m_btnReset"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 410);
         m_vDicts[2]["GUIEscMenu.m_btnSoundDn"] = new FlxPoint(_loc1_.x + 842,_loc1_.y + 72 + 104);
         m_vDicts[2]["GUIEscMenu.m_btnSoundUp"] = new FlxPoint(_loc1_.x + 842 + 74 + 52,_loc1_.y + 72 + 104);
         m_vDicts[2]["GUIEscMenu.m_btnStretch"] = new FlxPoint(_loc1_.x + 584,_loc1_.y + 536 + 104);
         m_vDicts[2]["GUIEscMenu.m_btnTerEdit"] = new FlxPoint(_loc1_.x + 627,_loc1_.y + 322);
         m_vDicts[2]["GUIEscMenu.m_btnWiki"] = new FlxPoint(_loc1_.x + 10,_loc1_.y + 106);
         m_vDicts[2]["GUIEscMenu.m_btnZomboid"] = new FlxPoint(_loc1_.x + 746,_loc1_.y + 732);
         m_vDicts[2]["GUIEscMenu.m_sprBugsBG"] = new FlxPoint(_loc1_.x + 278,_loc1_.y + 732);
         m_vDicts[2]["GUIEscMenu.m_sprCredits"] = new FlxPoint(_loc1_.x + 680,_loc1_.y + 384);
         m_vDicts[2]["GUIEscMenu.m_sprDialogBG"] = new FlxPoint(_loc1_.x + 604,_loc1_.y + 346);
         m_vDicts[2]["GUIEscMenu.m_sprDialogBG.size"] = new FlxPoint(150,70);
         m_vDicts[2]["GUIEscMenu.m_sprHelpCur"] = new FlxPoint(_loc1_.x + 870,_loc1_.y + 7);
         m_vDicts[2]["GUIEscMenu.m_sprHelpLClick"] = new FlxPoint(_loc1_.x + 292,_loc1_.y + 10);
         m_vDicts[2]["GUIEscMenu.m_sprHelpL2Click"] = new FlxPoint(_loc1_.x + 335,_loc1_.y + 311);
         m_vDicts[2]["GUIEscMenu.m_sprHelpPlayer"] = new FlxPoint(_loc1_.x - 87,_loc1_.y + 389);
         m_vDicts[2]["GUIEscMenu.m_sprHelpRClick"] = new FlxPoint(_loc1_.x + 1007,_loc1_.y + 325);
         m_vDicts[2]["GUIEscMenu.m_sprHelpSLClick"] = new FlxPoint(_loc1_.x + 309,_loc1_.y + 517);
         m_vDicts[2]["GUIEscMenu.m_sprHelpSpace"] = new FlxPoint(_loc1_.x + 500,_loc1_.y + 714);
         m_vDicts[2]["GUIEscMenu.m_sprHelpWASD"] = new FlxPoint(_loc1_.x + 870,_loc1_.y + 170);
         m_vDicts[2]["GUIEscMenu.m_sprInstr"] = new FlxPoint(_loc1_.x - 120,_loc1_.y + -62);
         m_vDicts[2]["GUIEscMenu.m_sprSparkle"] = new FlxPoint(_loc1_.x + 1202,_loc1_.y + 603);
         m_vDicts[2]["GUIEscMenu.m_sprTitle"] = new FlxPoint(_loc1_.x + 18,_loc1_.y + 16);
         m_vDicts[2]["GUIEscMenu.m_sprTitleGrass1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 226 + 109);
         m_vDicts[2]["GUIEscMenu.m_sprTitleIslands1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 303 + 109);
         m_vDicts[2]["GUIEscMenu.m_sprTitleMid1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 361 + 109);
         m_vDicts[2]["GUIEscMenu.m_sprTitleMtns1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 221 + 109);
         m_vDicts[2]["GUIEscMenu.m_sprTitleTrees1"] = new FlxPoint(_loc1_.x + 0,_loc1_.y + 123 + 109);
         m_vDicts[2]["GUIEscMenu.m_txtConfirm"] = new FlxPoint(_loc1_.x + 604,_loc1_.y + 359);
         m_vDicts[2]["GUIEscMenu.m_txtConfirm.width"] = 150;
         m_vDicts[2]["GUIEscMenu.m_txtCopyright"] = new FlxPoint(_loc1_.x + 404,_loc1_.y + 696);
         m_vDicts[2]["GUIEscMenu.m_txtCopyright.width"] = 552;
         m_vDicts[2]["GUIEscMenu.m_txtLoadingGame"] = new FlxPoint(_loc1_.x + 635,_loc1_.y + 113);
         m_vDicts[2]["GUIEscMenu.m_txtLoadingGame.width"] = 550;
         m_vDicts[2]["GUIEscMenu.m_txtMasterVolName.width"] = 74;
         m_vDicts[2]["GUIEscMenu.m_txtFPSName"] = new FlxPoint(_loc1_.x + 842 + 52 + 15,_loc1_.y + 72 + 21 + 260);
         m_vDicts[2]["GUIEscMenu.m_txtFPSValue"] = new FlxPoint(_loc1_.x + 842 + 52 + 74 + 52,_loc1_.y + 72 + 21 + 260);
         m_vDicts[2]["GUIEscMenu.m_txtMasterVolName"] = new FlxPoint(_loc1_.x + 842 + 52 + 2,_loc1_.y + 72 + 21);
         m_vDicts[2]["GUIEscMenu.m_txtMasterVolValue"] = new FlxPoint(_loc1_.x + 842 + 52 + 74 + 52,_loc1_.y + 72 + 21);
         m_vDicts[2]["GUIEscMenu.m_txtMusicVolName"] = new FlxPoint(_loc1_.x + 842 + 52 + 6,_loc1_.y + 72 + 21 + 52);
         m_vDicts[2]["GUIEscMenu.m_txtMusicVolValue"] = new FlxPoint(_loc1_.x + 842 + 52 + 74 + 52,_loc1_.y + 72 + 21 + 52);
         m_vDicts[2]["GUIEscMenu.m_txtSoundVolName"] = new FlxPoint(_loc1_.x + 842 + 52 + 4,_loc1_.y + 72 + 21 + 104);
         m_vDicts[2]["GUIEscMenu.m_txtSoundVolValue"] = new FlxPoint(_loc1_.x + 842 + 52 + 74 + 52,_loc1_.y + 72 + 21 + 104);
         m_vDicts[2]["GUIEscMenu.m_txtVersion"] = new FlxPoint(_loc1_.x + 308,_loc1_.y + 339);
         m_vDicts[2]["GUIEscMenu.m_txtVersion.width"] = 280;
         m_vDicts[2]["GUIEscMenu.txtCreditNames"] = new FlxPoint(_loc1_.x + 623,_loc1_.y + 180);
         m_vDicts[2]["GUIEscMenu.txtCreditNames.width"] = 544;
         m_vDicts[2]["GUIEscMenu.txtCreditRoles"] = new FlxPoint(_loc1_.x + 289,_loc1_.y + 180);
         m_vDicts[2]["GUIEscMenu.txtCreditRoles.width"] = 300;
         m_vDicts[2]["GUIEscMenu.m_sprSaveGameWarning"] = new FlxPoint(_loc1_.x + 917,_loc1_.y + 16);
         m_vDicts[2]["GUIEscMenu.m_sprSaveGameWarning.MoreInfo"] = new FlxPoint(_loc1_.x + 965,_loc1_.y + 279);
         m_vDicts[2]["GUIEscMenu.m_sprSaveGameWarning.Retry"] = new FlxPoint(_loc1_.x + 1035,_loc1_.y + 279);
         m_vDicts[2]["GUIEscMenu.UI.Zoom"] = 2;
         m_vDicts[2]["GUIEscMenu.m_sprCredits.Instr"] = new FlxPoint(_loc1_.x + 952,_loc1_.y + 384);
         m_vDicts[2]["GUIInventory.Backpack"] = new FlxPoint(_loc1_.x + 790,_loc1_.y + 59);
         m_vDicts[2]["GUIInventory.Backpack.Cap"] = new FlxPoint(_loc1_.x + 917,_loc1_.y + 0);
         m_vDicts[2]["GUIInventory.Body"] = new FlxPoint(_loc1_.x + 418,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.Body.CapBelt"] = new FlxPoint(_loc1_.x + 490,_loc1_.y + 390);
         m_vDicts[2]["GUIInventory.Body.CapLeftShoulder"] = new FlxPoint(_loc1_.x + 698,_loc1_.y + 1);
         m_vDicts[2]["GUIInventory.Body.CapLegs"] = new FlxPoint(_loc1_.x + 490,_loc1_.y + 490);
         m_vDicts[2]["GUIInventory.Body.CapRightShoulder"] = new FlxPoint(_loc1_.x + 490,_loc1_.y + 70);
         m_vDicts[2]["GUIInventory.Body.CapTorso"] = new FlxPoint(_loc1_.x + 490,_loc1_.y + 170);
         m_vDicts[2]["GUIInventory.btnCraftAvail"] = new FlxPoint(_loc1_.x + 217,_loc1_.y + 3);
         m_vDicts[2]["GUIInventory.btnCraftConfirm"] = new FlxPoint(_loc1_.x + 948,_loc1_.y + 260);
         m_vDicts[2]["GUIInventory.btnCraftRecipes"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 3);
         m_vDicts[2]["GUIInventory.btnEncConfirm"] = new FlxPoint(_loc1_.x + 1097,_loc1_.y + 414);
         m_vDicts[2]["GUIInventory.btnNextCraft"] = new FlxPoint(_loc1_.x + 479,_loc1_.y + 33);
         m_vDicts[2]["GUIInventory.btnNextYield"] = new FlxPoint(_loc1_.x + 1074,_loc1_.y + 260);
         m_vDicts[2]["GUIInventory.btnPrevCraft"] = new FlxPoint(_loc1_.x + 479,_loc1_.y + 85);
         m_vDicts[2]["GUIInventory.btnPrevYield"] = new FlxPoint(_loc1_.x + 896,_loc1_.y + 260);
         m_vDicts[2]["GUIInventory.btnSkillsConfirm"] = new FlxPoint(_loc1_.x + 648,_loc1_.y + 254);
         m_vDicts[2]["GUIInventory.btnSkillsRandom"] = new FlxPoint(_loc1_.x + 648,_loc1_.y + 324);
         m_vDicts[2]["GUIInventory.grpAvailCampSlot.Cap"] = new FlxPoint(_loc1_.x + 1225,_loc1_.y + 102);
         m_vDicts[2]["GUIInventory.grpAvailCraftItemsSlot.Cap"] = new FlxPoint(_loc1_.x + 73,_loc1_.y + 39);
         m_vDicts[2]["GUIInventory.grpAvailEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 362);
         m_vDicts[2]["GUIInventory.grpAvailSkillSlot.Cap"] = new FlxPoint(_loc1_.x + 69,_loc1_.y + 35);
         m_vDicts[2]["GUIInventory.grpAvailTraitSlot.Cap"] = new FlxPoint(_loc1_.x + 69,_loc1_.y + 355);
         m_vDicts[2]["GUIInventory.grpCampAlertness"] = new FlxPoint(_loc1_.x + 920,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.grpCampConcealment"] = new FlxPoint(_loc1_.x + 840,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.grpCampHealRate"] = new FlxPoint(_loc1_.x + 760,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.grpCampShelter"] = new FlxPoint(_loc1_.x + 600,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.grpCampSleepQuality"] = new FlxPoint(_loc1_.x + 680,_loc1_.y + 48);
         m_vDicts[2]["GUIInventory.grpCampSlot"] = new FlxPoint(_loc1_.x + 487,_loc1_.y + 36);
         m_vDicts[2]["GUIInventory.grpCampSlot.Cap"] = new FlxPoint(_loc1_.x + 487,_loc1_.y + 102);
         m_vDicts[2]["GUIInventory.grpCraftingIngredientsSlot.Cap"] = new FlxPoint(_loc1_.x + 656,_loc1_.y + 25);
         m_vDicts[2]["GUIInventory.grpCraftingYieldSlot.Cap"] = new FlxPoint(_loc1_.x + 656,_loc1_.y + 396);
         m_vDicts[2]["GUIInventory.grpEncounterSlot"] = new FlxPoint(_loc1_.x + 326,_loc1_.y + 182);
         m_vDicts[2]["GUIInventory.grpEncounterSlot.Cap"] = new FlxPoint(_loc1_.x + 529,_loc1_.y + 362);
         m_vDicts[2]["GUIInventory.grpEncounterSlot.zoom"] = 2;
         m_vDicts[2]["GUIInventory.grpGroundSlot.Cap"] = new FlxPoint(_loc1_.x + 65,_loc1_.y + 39);
         m_vDicts[2]["GUIInventory.grpHealthBlood"] = new FlxPoint(_loc1_.x + 1126,_loc1_.y + 533);
         m_vDicts[2]["GUIInventory.grpHealthInfection"] = new FlxPoint(_loc1_.x + 1126,_loc1_.y + 563);
         m_vDicts[2]["GUIInventory.grpHealthPain"] = new FlxPoint(_loc1_.x + 1126,_loc1_.y + 593);
         m_vDicts[2]["GUIInventory.grpScavengeAccident"] = new FlxPoint(_loc1_.x + 289,_loc1_.y + 314);
         m_vDicts[2]["GUIInventory.grpScavengeCreature"] = new FlxPoint(_loc1_.x + 489,_loc1_.y + 314);
         m_vDicts[2]["GUIInventory.grpScavengeLoot"] = new FlxPoint(_loc1_.x + 98,_loc1_.y + 314);
         m_vDicts[2]["GUIInventory.grpScavengeLoot.size"] = 110;
         m_vDicts[2]["GUIInventory.grpVehicleSlot"] = new FlxPoint(_loc1_.x + 946,_loc1_.y + 92);
         m_vDicts[2]["GUIInventory.grpVehicleSlot.Cap"] = new FlxPoint(_loc1_.x + 485,_loc1_.y + 220);
         m_vDicts[2]["GUIInventory.HoldLeft"] = new FlxPoint(_loc1_.x + 826,_loc1_.y + 461);
         m_vDicts[2]["GUIInventory.HoldLeft.Cap"] = new FlxPoint(_loc1_.x + 917,_loc1_.y + 412);
         m_vDicts[2]["GUIInventory.HoldRight"] = new FlxPoint(_loc1_.x + 826,_loc1_.y + 255);
         m_vDicts[2]["GUIInventory.HoldRight.Cap"] = new FlxPoint(_loc1_.x + 917,_loc1_.y + 206);
         m_vDicts[2]["GUIInventory.Neck"] = new FlxPoint(_loc1_.x + 511,_loc1_.y + -12);
         m_vDicts[2]["GUIInventory.QuickRecipe.size"] = new FlxPoint(400,21);
         m_vDicts[2]["GUIInventory.Skills"] = new FlxPoint(_loc1_.x + 872,_loc1_.y + 32);
         m_vDicts[2]["GUIInventory.sprBG"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[2]["GUIInventory.sprBG.size"] = new FlxPoint(1297,625);
         m_vDicts[2]["GUIInventory.sprCraftArrowDown"] = new FlxPoint(_loc1_.x + 976,_loc1_.y + 326);
         m_vDicts[2]["GUIInventory.sprCraftArrowRight"] = new FlxPoint(_loc1_.x + 552,_loc1_.y + 118);
         m_vDicts[2]["GUIInventory.sprSkillArrowRight"] = new FlxPoint(_loc1_.x + 680,_loc1_.y + 61);
         m_vDicts[2]["GUIInventory.sprTraitArrowRight"] = new FlxPoint(_loc1_.x + 680,_loc1_.y + 416);
         m_vDicts[2]["GUIInventory.sprCraftCapBG"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 33);
         m_vDicts[2]["GUIInventory.sprCraftCapBG.image"] = "GUICraftCapBG.png";
         m_vDicts[2]["GUIInventory.sprEncounter.size"] = new FlxPoint(260,180);
         m_vDicts[2]["GUIInventory.sprYieldCapBG"] = new FlxPoint(_loc1_.x + 650,_loc1_.y + 390);
         m_vDicts[2]["GUIInventory.Traits"] = new FlxPoint(_loc1_.x + 872,_loc1_.y + 355);
         m_vDicts[2]["GUIInventory.txtAvailCamp"] = new FlxPoint(_loc1_.x + 1246,_loc1_.y + 55);
         m_vDicts[2]["GUIInventory.txtAvailCamp.size"] = 120;
         m_vDicts[2]["GUIInventory.txtCamp"] = new FlxPoint(_loc1_.x + 490,_loc1_.y + 3);
         m_vDicts[2]["GUIInventory.txtCamp.size"] = 260;
         m_vDicts[2]["GUIInventory.txtCondStatsWarning"] = new FlxPoint(_loc1_.x + 1126,_loc1_.y + 533);
         m_vDicts[2]["GUIInventory.txtCondStatsWarning.size"] = 240;
         m_vDicts[2]["GUIInventory.txtCondTitle"] = new FlxPoint(_loc1_.x + 1136,_loc1_.y + 2);
         m_vDicts[2]["GUIInventory.txtCraftMoves"] = new FlxPoint(_loc1_.x + 855,_loc1_.y + 126);
         m_vDicts[2]["GUIInventory.txtCraftMoves.size"] = 390;
         m_vDicts[2]["GUIInventory.txtCraIngredients"] = new FlxPoint(_loc1_.x + 656,_loc1_.y + 4);
         m_vDicts[2]["GUIInventory.txtCraIngredients.size"] = 440;
         m_vDicts[2]["GUIInventory.txtCraYield"] = new FlxPoint(_loc1_.x + 656,_loc1_.y + 370);
         m_vDicts[2]["GUIInventory.txtCraYield.size"] = 640;
         m_vDicts[2]["GUIInventory.txtEncAvail"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 604);
         m_vDicts[2]["GUIInventory.txtEncAvail.size"] = 440;
         m_vDicts[2]["GUIInventory.txtEncounter"] = new FlxPoint(_loc1_.x + 593,_loc1_.y + 1);
         m_vDicts[2]["GUIInventory.txtEncounter.size"] = 767;
         m_vDicts[2]["GUIInventory.txtEncResponse"] = new FlxPoint(_loc1_.x + 977,_loc1_.y + 363);
         m_vDicts[2]["GUIInventory.txtEncResponse.size"] = 383;
         m_vDicts[2]["GUIInventory.txtEncResponseLabel"] = new FlxPoint(_loc1_.x + 529,_loc1_.y + 604);
         m_vDicts[2]["GUIInventory.txtEncResponseLabel.size"] = 440;
         m_vDicts[2]["GUIInventory.txtGroundAvail"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 7);
         m_vDicts[2]["GUIInventory.txtSkillSpace1"] = new FlxPoint(_loc1_.x + 872,_loc1_.y + 7);
         m_vDicts[2]["GUIInventory.txtSkillSpace1.size"] = 160;
         m_vDicts[2]["GUIInventory.txtSkillTotal"] = new FlxPoint(_loc1_.x + 641,_loc1_.y + 150);
         m_vDicts[2]["GUIInventory.txtSklAvail"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 7);
         m_vDicts[2]["GUIInventory.txtSklAvail.size"] = 480;
         m_vDicts[2]["GUIInventory.txtTraitAvail"] = new FlxPoint(_loc1_.x + 67,_loc1_.y + 328);
         m_vDicts[2]["GUIInventory.txtTraitAvail.size"] = 480;
         m_vDicts[2]["GUIInventory.txtTraitInstruct"] = new FlxPoint(_loc1_.x + 564,_loc1_.y + 498);
         m_vDicts[2]["GUIInventory.txtTraitInstruct.size"] = 294;
         m_vDicts[2]["GUIInventory.txtTraitSlot1"] = new FlxPoint(_loc1_.x + 872,_loc1_.y + 328);
         m_vDicts[2]["GUIInventory.txtTraitSlot1.size"] = 160;
         m_vDicts[2]["height"] = 768;
         m_vDicts[2]["Item.zoom"] = 2;
         m_vDicts[2]["Minimap"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 0);
         m_vDicts[2]["Minimap.size"] = new FlxPoint(1297,625);
         m_vDicts[2]["Minimap.zoom"] = 2;
         m_vDicts[2]["nBodyFontColor"] = 16777215;
         m_vDicts[2]["nBodyFontShadowColor"] = 4278190080;
         m_vDicts[2]["nBodyFontSize"] = 32;
         m_vDicts[2]["nLabelFontSize"] = 32;
         m_vDicts[2]["nTinyFontSize"] = 16;
         m_vDicts[2]["offset"] = new FlxPoint(_loc1_.x,_loc1_.y);
         m_vDicts[2]["PlayState.btnAmodeDn"] = new FlxPoint(_loc1_.x + 960,_loc1_.y + 732);
         m_vDicts[2]["PlayState.btnAmodeUp"] = new FlxPoint(_loc1_.x + 960,_loc1_.y + 686);
         m_vDicts[2]["PlayState.btnItems"] = new FlxPoint(_loc1_.x,_loc1_.y + 610);
         m_vDicts[2]["PlayState.btnMainMap"] = new FlxPoint(_loc1_.x,_loc1_.y + 410);
         m_vDicts[2]["PlayState.btnWait"] = new FlxPoint(_loc1_.x,_loc1_.y + 250);
         m_vDicts[2]["PlayState.camMsg"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 625);
         m_vDicts[2]["PlayState.camMsg.btnFont"] = new FlxPoint(861,42);
         m_vDicts[2]["PlayState.camMsg.btnExpand"] = new FlxPoint(861,8);
         m_vDicts[2]["PlayState.camMsg.maxheight"] = 343;
         m_vDicts[2]["PlayState.camMsg.minheight"] = 143;
         m_vDicts[2]["PlayState.camMsg.width"] = 899;
         m_vDicts[2]["PlayState.grpAttackMode.zoom"] = 2;
         m_vDicts[2]["PlayState.grpAttackMode.ChargeHeight"] = 768;
         m_vDicts[2]["PlayState.GUIMessageWindow.m_sprBG.bigimage"] = "GUIMessageFrameBig_1360x768.png";
         m_vDicts[2]["PlayState.m_txtLoadMessage"] = new FlxPoint(_loc1_.x + 350,_loc1_.y + 350);
         m_vDicts[2]["PlayState.sprAttackModeBG"] = new FlxPoint(_loc1_.x + 960,_loc1_.y + 625);
         m_vDicts[2]["PlayState.sprAttackModeBG.image"] = "AModeFrame_1360x768.png";
         m_vDicts[2]["PlayState.sprAttackModeChargeOffset"] = 4;
         m_vDicts[2]["PlayState.sprCorner"] = new FlxPoint(_loc1_.x + 960,_loc1_.y + 625);
         m_vDicts[2]["PlayState.txtAttackMode"] = new FlxPoint(_loc1_.x + 1008,_loc1_.y + 627);
         m_vDicts[2]["PlayState.txtAttackMode.width"] = 400;
         m_vDicts[2]["PlayState.txtAttackModeCharges"] = new FlxPoint(_loc1_.x + 1312,_loc1_.y + 736);
         m_vDicts[2]["PlayState.txtAttackModeCharges.width"] = 48;
         m_vDicts[2]["PlayState.txtHexInfo"] = new FlxPoint(_loc1_.x + 63,_loc1_.y + 625);
         m_vDicts[2]["PlayState.txtHexInfo.width"] = 400;
         m_vDicts[2]["PlayState.txtMovesLeftReserve"] = new FlxPoint(63,4);
         m_vDicts[2]["strAlignMode"] = "";
         m_vDicts[2]["strBodyFontName"] = "pixelmid";
         m_vDicts[2]["strLabelFontName"] = "pixelmid";
         m_vDicts[2]["strScaleMode"] = StageScaleMode.NO_SCALE;
         m_vDicts[2]["strTinyFontName"] = "pixeltiny";
         m_vDicts[2]["TextPopUp.width"] = 340;
         m_vDicts[2]["WeatherNode"] = new FlxPoint(_loc1_.x + 1278,_loc1_.y);
         m_vDicts[2]["width"] = 1360;
         m_vDicts[2]["zoom"] = 1;
         for(_loc2_ in m_vDicts[0])
         {
            m_vDicts[3][_loc2_] = m_vDicts[0][_loc2_];
            m_vDicts[4][_loc2_] = m_vDicts[0][_loc2_];
         }
         m_vDicts[3]["zoom"] = 2;
         m_vDicts[4]["zoom"] = 3;
      }
      
      public static function ScaleBitmapData(param1:BitmapData, param2:Number, param3:Number = 0) : BitmapData
      {
         if(param1 == null || param2 == 0)
         {
            return param1;
         }
         param2 = Math.abs(param2);
         var _loc4_:int = param1.width * param2;
         var _loc5_:int = param1.height * param2;
         if(param3 != 0)
         {
            _loc5_ = param1.height * param3;
         }
         var _loc6_:Boolean = param1.transparent;
         var _loc7_:BitmapData = new BitmapData(_loc4_,_loc5_,_loc6_,0);
         var _loc8_:Matrix;
         (_loc8_ = new Matrix()).scale(param2,param2);
         _loc7_.draw(param1,_loc8_);
         return _loc7_;
      }
      
      public static function GetPoint(param1:String, param2:FlxPoint = null) : FlxPoint
      {
         ptTemp = m_vDicts[m_nGUIType][param1];
         if(param2 == null)
         {
            return new FlxPoint(ptTemp.x,ptTemp.y);
         }
         param2.x = ptTemp.x;
         param2.y = ptTemp.y;
         return param2;
      }
      
      public static function GetInt(param1:String) : int
      {
         return m_vDicts[m_nGUIType][param1];
      }
      
      public static function GetString(param1:String) : String
      {
         return m_vDicts[m_nGUIType][param1];
      }
      
      public static function GetBool(param1:String) : Boolean
      {
         return m_vDicts[m_nGUIType][param1];
      }
      
      public static function SetString(param1:int, param2:String, param3:String) : void
      {
         m_vDicts[param1][param2] = param3;
      }
      
      public static function SetPosition(param1:FlxObject, param2:String) : void
      {
         var _loc3_:FlxPoint = GetPoint(param2);
         param1.x = _loc3_.x;
         param1.y = _loc3_.y;
      }
   }
}
