using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Reflection;
using System.Text.Json;

namespace NeoEditor.Data.Model;

/// <summary>
/// Authoritative per-field descriptions embedded from
/// <c>Docs/38-full-field-reference.md</c> (verified against original data/*.xml,
/// 2026-08-02). Generated by <c>artifacts/gen-field-descriptions.js</c>.
///
/// Same pattern as <see cref="FieldGroupMetadata"/> — static immutable lookup,
/// no mutable static state (N01). Available to every project that references Core.
/// </summary>
public static class FieldDescriptions
{
    private static readonly Dictionary<string, string> Descriptions = Load();

    private static Dictionary<string, string> Load()
    {
        try
        {
            var asm = typeof(FieldDescriptions).Assembly;
            using var stream = asm.GetManifestResourceStream("NeoEditor.Core.Model.field_descriptions.json");
            if (stream is null) return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            using var reader = new StreamReader(stream);
            var dict = JsonSerializer.Deserialize<Dictionary<string, string>>(reader.ReadToEnd());
            return dict is null
                ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                : new Dictionary<string, string>(dict, StringComparer.OrdinalIgnoreCase);
        }
        catch (Exception)
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        }
    }

    /// <summary>Get field description by entity type + C# property name.</summary>
    public static string? GetDescription(Type entityType, string propertyName)
    {
        if (entityType is null || string.IsNullOrEmpty(propertyName)) return null;
        var table = entityType.GetCustomAttribute<TableAttribute>()?.Name
                    ?? entityType.Name.ToLowerInvariant();
        return GetDescription(table, propertyName);
    }

    /// <summary>
    /// Get field description by table name + property name (case-insensitive).
    /// Editor-internal IEntity columns (ModId/FilePath/EntityId) match any table via "*." prefix.
    /// </summary>
    public static string? GetDescription(string tableName, string propertyName)
    {
        if (string.IsNullOrWhiteSpace(tableName) || string.IsNullOrWhiteSpace(propertyName)) return null;
        if (Descriptions.TryGetValue($"{tableName}.{propertyName}", out var desc)) return desc;
        return Descriptions.TryGetValue($"*.{propertyName}", out var generic) ? generic : null;
    }

    /// <summary>All embedded entries (for tests / diagnostics).</summary>
    public static IReadOnlyDictionary<string, string> All => Descriptions;
}
